/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#include "Acknowledgement.h"

static asn_TYPE_member_t asn_MBR_Acknowledgement_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Acknowledgement, sender),
		(ASN_TAG_CLASS_APPLICATION | (196 << 2)),
		0,
		&asn_DEF_Sender,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sender"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Acknowledgement, recipient),
		(ASN_TAG_CLASS_APPLICATION | (182 << 2)),
		0,
		&asn_DEF_Recipient,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recipient"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Acknowledgement, rapFileSequenceNumber),
		(ASN_TAG_CLASS_APPLICATION | (181 << 2)),
		0,
		&asn_DEF_RapFileSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rapFileSequenceNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Acknowledgement, ackFileCreationTimeStamp),
		(ASN_TAG_CLASS_APPLICATION | (516 << 2)),
		0,
		&asn_DEF_AckFileCreationTimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ackFileCreationTimeStamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Acknowledgement, ackFileAvailableTimeStamp),
		(ASN_TAG_CLASS_APPLICATION | (515 << 2)),
		0,
		&asn_DEF_AckFileAvailableTimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ackFileAvailableTimeStamp"
		},
	{ ATF_POINTER, 2, offsetof(struct Acknowledgement, fileTypeIndicator),
		(ASN_TAG_CLASS_APPLICATION | (110 << 2)),
		0,
		&asn_DEF_FileTypeIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fileTypeIndicator"
		},
	{ ATF_POINTER, 1, offsetof(struct Acknowledgement, operatorSpecList),
		(ASN_TAG_CLASS_APPLICATION | (551 << 2)),
		0,
		&asn_DEF_OperatorSpecList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operatorSpecList"
		},
};
static ber_tlv_tag_t asn_DEF_Acknowledgement_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (535 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Acknowledgement_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (110 << 2)), 5, 0, 0 }, /* fileTypeIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (181 << 2)), 2, 0, 0 }, /* rapFileSequenceNumber */
    { (ASN_TAG_CLASS_APPLICATION | (182 << 2)), 1, 0, 0 }, /* recipient */
    { (ASN_TAG_CLASS_APPLICATION | (196 << 2)), 0, 0, 0 }, /* sender */
    { (ASN_TAG_CLASS_APPLICATION | (515 << 2)), 4, 0, 0 }, /* ackFileAvailableTimeStamp */
    { (ASN_TAG_CLASS_APPLICATION | (516 << 2)), 3, 0, 0 }, /* ackFileCreationTimeStamp */
    { (ASN_TAG_CLASS_APPLICATION | (551 << 2)), 6, 0, 0 } /* operatorSpecList */
};
static asn_SEQUENCE_specifics_t asn_SPC_Acknowledgement_specs_1 = {
	sizeof(struct Acknowledgement),
	offsetof(struct Acknowledgement, _asn_ctx),
	asn_MAP_Acknowledgement_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	6,	/* Start extensions */
	8	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Acknowledgement = {
	"Acknowledgement",
	"Acknowledgement",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Acknowledgement_tags_1,
	sizeof(asn_DEF_Acknowledgement_tags_1)
		/sizeof(asn_DEF_Acknowledgement_tags_1[0]) - 1, /* 1 */
	asn_DEF_Acknowledgement_tags_1,	/* Same as above */
	sizeof(asn_DEF_Acknowledgement_tags_1)
		/sizeof(asn_DEF_Acknowledgement_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_Acknowledgement_1,
	7,	/* Elements count */
	&asn_SPC_Acknowledgement_specs_1	/* Additional specs */
};

