/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "BasicServiceCode.h"

static asn_TYPE_member_t asn_MBR_BasicServiceCode_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BasicServiceCode, choice.teleServiceCode),
		(ASN_TAG_CLASS_APPLICATION | (218 << 2)),
		0,
		&asn_DEF_TeleServiceCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"teleServiceCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BasicServiceCode, choice.bearerServiceCode),
		(ASN_TAG_CLASS_APPLICATION | (40 << 2)),
		0,
		&asn_DEF_BearerServiceCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bearerServiceCode"
		},
};
static ber_tlv_tag_t asn_DEF_BasicServiceCode_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (426 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BasicServiceCode_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (40 << 2)), 1, 0, 0 }, /* bearerServiceCode */
    { (ASN_TAG_CLASS_APPLICATION | (218 << 2)), 0, 0, 0 } /* teleServiceCode */
};
static asn_CHOICE_specifics_t asn_SPC_BasicServiceCode_specs_1 = {
	sizeof(struct BasicServiceCode),
	offsetof(struct BasicServiceCode, _asn_ctx),
	offsetof(struct BasicServiceCode, present),
	sizeof(((struct BasicServiceCode *)0)->present),
	asn_MAP_BasicServiceCode_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_BasicServiceCode = {
	"BasicServiceCode",
	"BasicServiceCode",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	asn_DEF_BasicServiceCode_tags_1,
	sizeof(asn_DEF_BasicServiceCode_tags_1)
		/sizeof(asn_DEF_BasicServiceCode_tags_1[0]), /* 1 */
	asn_DEF_BasicServiceCode_tags_1,	/* Same as above */
	sizeof(asn_DEF_BasicServiceCode_tags_1)
		/sizeof(asn_DEF_BasicServiceCode_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BasicServiceCode_1,
	2,	/* Elements count */
	&asn_SPC_BasicServiceCode_specs_1	/* Additional specs */
};

