/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_CallTypeGroup_H_
#define	_CallTypeGroup_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallTypeLevel1.h"
#include "CallTypeLevel2.h"
#include "CallTypeLevel3.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CallTypeGroup */
typedef struct CallTypeGroup {
	CallTypeLevel1_t	*callTypeLevel1	/* OPTIONAL */;
	CallTypeLevel2_t	*callTypeLevel2	/* OPTIONAL */;
	CallTypeLevel3_t	*callTypeLevel3	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallTypeGroup_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallTypeGroup;

#ifdef __cplusplus
}
#endif

#endif	/* _CallTypeGroup_H_ */
#include <asn_internal.h>
