/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_ChargeInformationList_H_
#define	_ChargeInformationList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargeInformation;

/* ChargeInformationList */
typedef struct ChargeInformationList {
	A_SEQUENCE_OF(struct ChargeInformation) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChargeInformationList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargeInformationList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargeInformation.h"

#endif	/* _ChargeInformationList_H_ */
#include <asn_internal.h>
