/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_ContentTransactionType_H_
#define	_ContentTransactionType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ContentTransactionType */
typedef long	 ContentTransactionType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContentTransactionType;
asn_struct_free_f ContentTransactionType_free;
asn_struct_print_f ContentTransactionType_print;
asn_constr_check_f ContentTransactionType_constraint;
ber_type_decoder_f ContentTransactionType_decode_ber;
der_type_encoder_f ContentTransactionType_encode_der;
xer_type_decoder_f ContentTransactionType_decode_xer;
xer_type_encoder_f ContentTransactionType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ContentTransactionType_H_ */
#include <asn_internal.h>
