/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_ContentProviderIdList_H_
#define	_ContentProviderIdList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ContentProvider;

/* ContentProviderIdList */
typedef struct ContentProviderIdList {
	A_SEQUENCE_OF(struct ContentProvider) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ContentProviderIdList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContentProviderIdList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ContentProvider.h"

#endif	/* _ContentProviderIdList_H_ */
#include <asn_internal.h>
