/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_CustomerIdentifier_H_
#define	_CustomerIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CustomerIdentifier */
typedef AsciiString_t	 CustomerIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CustomerIdentifier;
asn_struct_free_f CustomerIdentifier_free;
asn_struct_print_f CustomerIdentifier_print;
asn_constr_check_f CustomerIdentifier_constraint;
ber_type_decoder_f CustomerIdentifier_decode_ber;
der_type_encoder_f CustomerIdentifier_encode_der;
xer_type_decoder_f CustomerIdentifier_decode_xer;
xer_type_encoder_f CustomerIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CustomerIdentifier_H_ */
#include <asn_internal.h>
