/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_DataVolumeIncoming_H_
#define	_DataVolumeIncoming_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DataVolume.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DataVolumeIncoming */
typedef DataVolume_t	 DataVolumeIncoming_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataVolumeIncoming;
asn_struct_free_f DataVolumeIncoming_free;
asn_struct_print_f DataVolumeIncoming_print;
asn_constr_check_f DataVolumeIncoming_constraint;
ber_type_decoder_f DataVolumeIncoming_decode_ber;
der_type_encoder_f DataVolumeIncoming_encode_der;
xer_type_decoder_f DataVolumeIncoming_decode_xer;
xer_type_encoder_f DataVolumeIncoming_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DataVolumeIncoming_H_ */
#include <asn_internal.h>
