/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "DataInterChange.h"

static asn_TYPE_member_t asn_MBR_DataInterChange_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DataInterChange, choice.transferBatch),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_TransferBatch,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transferBatch"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataInterChange, choice.notification),
		(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
		0,
		&asn_DEF_Notification,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"notification"
		},
};
static asn_TYPE_tag2member_t asn_MAP_DataInterChange_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 0, 0, 0 }, /* transferBatch */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 1, 0, 0 } /* notification */
};
static asn_CHOICE_specifics_t asn_SPC_DataInterChange_specs_1 = {
	sizeof(struct DataInterChange),
	offsetof(struct DataInterChange, _asn_ctx),
	offsetof(struct DataInterChange, present),
	sizeof(((struct DataInterChange *)0)->present),
	asn_MAP_DataInterChange_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_DataInterChange = {
	"DataInterChange",
	"DataInterChange",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_DataInterChange_1,
	2,	/* Elements count */
	&asn_SPC_DataInterChange_specs_1	/* Additional specs */
};

