/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "Destination.h"

static asn_TYPE_member_t asn_MBR_Destination_1[] = {
	{ ATF_POINTER, 5, offsetof(struct Destination, calledNumber),
		(ASN_TAG_CLASS_APPLICATION | (407 << 2)),
		0,
		&asn_DEF_CalledNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"calledNumber"
		},
	{ ATF_POINTER, 4, offsetof(struct Destination, dialledDigits),
		(ASN_TAG_CLASS_APPLICATION | (279 << 2)),
		0,
		&asn_DEF_DialledDigits,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dialledDigits"
		},
	{ ATF_POINTER, 3, offsetof(struct Destination, calledPlace),
		(ASN_TAG_CLASS_APPLICATION | (42 << 2)),
		0,
		&asn_DEF_CalledPlace,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"calledPlace"
		},
	{ ATF_POINTER, 2, offsetof(struct Destination, calledRegion),
		(ASN_TAG_CLASS_APPLICATION | (46 << 2)),
		0,
		&asn_DEF_CalledRegion,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"calledRegion"
		},
	{ ATF_POINTER, 1, offsetof(struct Destination, sMSDestinationNumber),
		(ASN_TAG_CLASS_APPLICATION | (419 << 2)),
		0,
		&asn_DEF_SMSDestinationNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sMSDestinationNumber"
		},
};
static ber_tlv_tag_t asn_DEF_Destination_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (89 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Destination_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (42 << 2)), 2, 0, 0 }, /* calledPlace */
    { (ASN_TAG_CLASS_APPLICATION | (46 << 2)), 3, 0, 0 }, /* calledRegion */
    { (ASN_TAG_CLASS_APPLICATION | (279 << 2)), 1, 0, 0 }, /* dialledDigits */
    { (ASN_TAG_CLASS_APPLICATION | (407 << 2)), 0, 0, 0 }, /* calledNumber */
    { (ASN_TAG_CLASS_APPLICATION | (419 << 2)), 4, 0, 0 } /* sMSDestinationNumber */
};
static asn_SEQUENCE_specifics_t asn_SPC_Destination_specs_1 = {
	sizeof(struct Destination),
	offsetof(struct Destination, _asn_ctx),
	asn_MAP_Destination_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Destination = {
	"Destination",
	"Destination",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Destination_tags_1,
	sizeof(asn_DEF_Destination_tags_1)
		/sizeof(asn_DEF_Destination_tags_1[0]) - 1, /* 1 */
	asn_DEF_Destination_tags_1,	/* Same as above */
	sizeof(asn_DEF_Destination_tags_1)
		/sizeof(asn_DEF_Destination_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_Destination_1,
	5,	/* Elements count */
	&asn_SPC_Destination_specs_1	/* Additional specs */
};

