/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_DiscountRate_H_
#define	_DiscountRate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PercentageRate.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DiscountRate */
typedef PercentageRate_t	 DiscountRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiscountRate;
asn_struct_free_f DiscountRate_free;
asn_struct_print_f DiscountRate_print;
asn_constr_check_f DiscountRate_constraint;
ber_type_decoder_f DiscountRate_decode_ber;
der_type_encoder_f DiscountRate_encode_der;
xer_type_decoder_f DiscountRate_decode_xer;
xer_type_encoder_f DiscountRate_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DiscountRate_H_ */
#include <asn_internal.h>
