/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_EndMissingSeqNumber_H_
#define	_EndMissingSeqNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FileSequenceNumber.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EndMissingSeqNumber */
typedef FileSequenceNumber_t	 EndMissingSeqNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EndMissingSeqNumber;
asn_struct_free_f EndMissingSeqNumber_free;
asn_struct_print_f EndMissingSeqNumber_print;
asn_constr_check_f EndMissingSeqNumber_constraint;
ber_type_decoder_f EndMissingSeqNumber_decode_ber;
der_type_encoder_f EndMissingSeqNumber_encode_der;
xer_type_decoder_f EndMissingSeqNumber_decode_xer;
xer_type_encoder_f EndMissingSeqNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EndMissingSeqNumber_H_ */
#include <asn_internal.h>
