/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_EquipmentId_H_
#define	_EquipmentId_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EquipmentId */
typedef AsciiString_t	 EquipmentId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EquipmentId;
asn_struct_free_f EquipmentId_free;
asn_struct_print_f EquipmentId_print;
asn_constr_check_f EquipmentId_constraint;
ber_type_decoder_f EquipmentId_decode_ber;
der_type_encoder_f EquipmentId_encode_der;
xer_type_decoder_f EquipmentId_decode_xer;
xer_type_encoder_f EquipmentId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EquipmentId_H_ */
#include <asn_internal.h>
