/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_HomeIdType_H_
#define	_HomeIdType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HomeIdType */
typedef long	 HomeIdType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HomeIdType;
asn_struct_free_f HomeIdType_free;
asn_struct_print_f HomeIdType_print;
asn_constr_check_f HomeIdType_constraint;
ber_type_decoder_f HomeIdType_decode_ber;
der_type_encoder_f HomeIdType_encode_der;
xer_type_decoder_f HomeIdType_decode_xer;
xer_type_encoder_f HomeIdType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HomeIdType_H_ */
#include <asn_internal.h>
