/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "ImeiOrEsn.h"

static asn_TYPE_member_t asn_MBR_ImeiOrEsn_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ImeiOrEsn, choice.imei),
		(ASN_TAG_CLASS_APPLICATION | (128 << 2)),
		0,
		&asn_DEF_Imei,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imei"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ImeiOrEsn, choice.esn),
		(ASN_TAG_CLASS_APPLICATION | (103 << 2)),
		0,
		&asn_DEF_Esn,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"esn"
		},
};
static ber_tlv_tag_t asn_DEF_ImeiOrEsn_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (429 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ImeiOrEsn_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (103 << 2)), 1, 0, 0 }, /* esn */
    { (ASN_TAG_CLASS_APPLICATION | (128 << 2)), 0, 0, 0 } /* imei */
};
static asn_CHOICE_specifics_t asn_SPC_ImeiOrEsn_specs_1 = {
	sizeof(struct ImeiOrEsn),
	offsetof(struct ImeiOrEsn, _asn_ctx),
	offsetof(struct ImeiOrEsn, present),
	sizeof(((struct ImeiOrEsn *)0)->present),
	asn_MAP_ImeiOrEsn_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ImeiOrEsn = {
	"ImeiOrEsn",
	"ImeiOrEsn",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	asn_DEF_ImeiOrEsn_tags_1,
	sizeof(asn_DEF_ImeiOrEsn_tags_1)
		/sizeof(asn_DEF_ImeiOrEsn_tags_1[0]), /* 1 */
	asn_DEF_ImeiOrEsn_tags_1,	/* Same as above */
	sizeof(asn_DEF_ImeiOrEsn_tags_1)
		/sizeof(asn_DEF_ImeiOrEsn_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ImeiOrEsn_1,
	2,	/* Elements count */
	&asn_SPC_ImeiOrEsn_specs_1	/* Additional specs */
};

