/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_ItemLevel_H_
#define	_ItemLevel_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ItemLevel */
typedef long	 ItemLevel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ItemLevel;
asn_struct_free_f ItemLevel_free;
asn_struct_print_f ItemLevel_print;
asn_constr_check_f ItemLevel_constraint;
ber_type_decoder_f ItemLevel_decode_ber;
der_type_encoder_f ItemLevel_encode_der;
xer_type_decoder_f ItemLevel_decode_xer;
xer_type_encoder_f ItemLevel_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ItemLevel_H_ */
#include <asn_internal.h>
