/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "LCSQosDelivered.h"

static asn_TYPE_member_t asn_MBR_LCSQosDelivered_1[] = {
	{ ATF_POINTER, 8, offsetof(struct LCSQosDelivered, lCSTransactionStatus),
		(ASN_TAG_CLASS_APPLICATION | (391 << 2)),
		0,
		&asn_DEF_LCSTransactionStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lCSTransactionStatus"
		},
	{ ATF_POINTER, 7, offsetof(struct LCSQosDelivered, horizontalAccuracyDelivered),
		(ASN_TAG_CLASS_APPLICATION | (392 << 2)),
		0,
		&asn_DEF_HorizontalAccuracyDelivered,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"horizontalAccuracyDelivered"
		},
	{ ATF_POINTER, 6, offsetof(struct LCSQosDelivered, verticalAccuracyDelivered),
		(ASN_TAG_CLASS_APPLICATION | (393 << 2)),
		0,
		&asn_DEF_VerticalAccuracyDelivered,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"verticalAccuracyDelivered"
		},
	{ ATF_POINTER, 5, offsetof(struct LCSQosDelivered, responseTime),
		(ASN_TAG_CLASS_APPLICATION | (394 << 2)),
		0,
		&asn_DEF_ResponseTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"responseTime"
		},
	{ ATF_POINTER, 4, offsetof(struct LCSQosDelivered, positioningMethod),
		(ASN_TAG_CLASS_APPLICATION | (395 << 2)),
		0,
		&asn_DEF_PositioningMethod,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"positioningMethod"
		},
	{ ATF_POINTER, 3, offsetof(struct LCSQosDelivered, trackingPeriod),
		(ASN_TAG_CLASS_APPLICATION | (388 << 2)),
		0,
		&asn_DEF_TrackingPeriod,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackingPeriod"
		},
	{ ATF_POINTER, 2, offsetof(struct LCSQosDelivered, trackingFrequency),
		(ASN_TAG_CLASS_APPLICATION | (389 << 2)),
		0,
		&asn_DEF_TrackingFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackingFrequency"
		},
	{ ATF_POINTER, 1, offsetof(struct LCSQosDelivered, ageOfLocation),
		(ASN_TAG_CLASS_APPLICATION | (396 << 2)),
		0,
		&asn_DEF_AgeOfLocation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ageOfLocation"
		},
};
static ber_tlv_tag_t asn_DEF_LCSQosDelivered_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (390 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_LCSQosDelivered_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (388 << 2)), 5, 0, 0 }, /* trackingPeriod */
    { (ASN_TAG_CLASS_APPLICATION | (389 << 2)), 6, 0, 0 }, /* trackingFrequency */
    { (ASN_TAG_CLASS_APPLICATION | (391 << 2)), 0, 0, 0 }, /* lCSTransactionStatus */
    { (ASN_TAG_CLASS_APPLICATION | (392 << 2)), 1, 0, 0 }, /* horizontalAccuracyDelivered */
    { (ASN_TAG_CLASS_APPLICATION | (393 << 2)), 2, 0, 0 }, /* verticalAccuracyDelivered */
    { (ASN_TAG_CLASS_APPLICATION | (394 << 2)), 3, 0, 0 }, /* responseTime */
    { (ASN_TAG_CLASS_APPLICATION | (395 << 2)), 4, 0, 0 }, /* positioningMethod */
    { (ASN_TAG_CLASS_APPLICATION | (396 << 2)), 7, 0, 0 } /* ageOfLocation */
};
static asn_SEQUENCE_specifics_t asn_SPC_LCSQosDelivered_specs_1 = {
	sizeof(struct LCSQosDelivered),
	offsetof(struct LCSQosDelivered, _asn_ctx),
	asn_MAP_LCSQosDelivered_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	7,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LCSQosDelivered = {
	"LCSQosDelivered",
	"LCSQosDelivered",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LCSQosDelivered_tags_1,
	sizeof(asn_DEF_LCSQosDelivered_tags_1)
		/sizeof(asn_DEF_LCSQosDelivered_tags_1[0]) - 1, /* 1 */
	asn_DEF_LCSQosDelivered_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCSQosDelivered_tags_1)
		/sizeof(asn_DEF_LCSQosDelivered_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_LCSQosDelivered_1,
	8,	/* Elements count */
	&asn_SPC_LCSQosDelivered_specs_1	/* Additional specs */
};

