/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "LCSQosRequested.h"

static asn_TYPE_member_t asn_MBR_LCSQosRequested_1[] = {
	{ ATF_POINTER, 6, offsetof(struct LCSQosRequested, lCSRequestTimestamp),
		(ASN_TAG_CLASS_APPLICATION | (384 << 2)),
		0,
		&asn_DEF_LCSRequestTimestamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lCSRequestTimestamp"
		},
	{ ATF_POINTER, 5, offsetof(struct LCSQosRequested, horizontalAccuracyRequested),
		(ASN_TAG_CLASS_APPLICATION | (385 << 2)),
		0,
		&asn_DEF_HorizontalAccuracyRequested,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"horizontalAccuracyRequested"
		},
	{ ATF_POINTER, 4, offsetof(struct LCSQosRequested, verticalAccuracyRequested),
		(ASN_TAG_CLASS_APPLICATION | (386 << 2)),
		0,
		&asn_DEF_VerticalAccuracyRequested,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"verticalAccuracyRequested"
		},
	{ ATF_POINTER, 3, offsetof(struct LCSQosRequested, responseTimeCategory),
		(ASN_TAG_CLASS_APPLICATION | (387 << 2)),
		0,
		&asn_DEF_ResponseTimeCategory,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"responseTimeCategory"
		},
	{ ATF_POINTER, 2, offsetof(struct LCSQosRequested, trackingPeriod),
		(ASN_TAG_CLASS_APPLICATION | (388 << 2)),
		0,
		&asn_DEF_TrackingPeriod,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackingPeriod"
		},
	{ ATF_POINTER, 1, offsetof(struct LCSQosRequested, trackingFrequency),
		(ASN_TAG_CLASS_APPLICATION | (389 << 2)),
		0,
		&asn_DEF_TrackingFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackingFrequency"
		},
};
static ber_tlv_tag_t asn_DEF_LCSQosRequested_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (383 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_LCSQosRequested_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (384 << 2)), 0, 0, 0 }, /* lCSRequestTimestamp */
    { (ASN_TAG_CLASS_APPLICATION | (385 << 2)), 1, 0, 0 }, /* horizontalAccuracyRequested */
    { (ASN_TAG_CLASS_APPLICATION | (386 << 2)), 2, 0, 0 }, /* verticalAccuracyRequested */
    { (ASN_TAG_CLASS_APPLICATION | (387 << 2)), 3, 0, 0 }, /* responseTimeCategory */
    { (ASN_TAG_CLASS_APPLICATION | (388 << 2)), 4, 0, 0 }, /* trackingPeriod */
    { (ASN_TAG_CLASS_APPLICATION | (389 << 2)), 5, 0, 0 } /* trackingFrequency */
};
static asn_SEQUENCE_specifics_t asn_SPC_LCSQosRequested_specs_1 = {
	sizeof(struct LCSQosRequested),
	offsetof(struct LCSQosRequested, _asn_ctx),
	asn_MAP_LCSQosRequested_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LCSQosRequested = {
	"LCSQosRequested",
	"LCSQosRequested",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LCSQosRequested_tags_1,
	sizeof(asn_DEF_LCSQosRequested_tags_1)
		/sizeof(asn_DEF_LCSQosRequested_tags_1[0]) - 1, /* 1 */
	asn_DEF_LCSQosRequested_tags_1,	/* Same as above */
	sizeof(asn_DEF_LCSQosRequested_tags_1)
		/sizeof(asn_DEF_LCSQosRequested_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_LCSQosRequested_1,
	6,	/* Elements count */
	&asn_SPC_LCSQosRequested_specs_1	/* Additional specs */
};

