/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_MessageType_H_
#define	_MessageType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MessageType */
typedef long	 MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageType;
asn_struct_free_f MessageType_free;
asn_struct_print_f MessageType_print;
asn_constr_check_f MessageType_constraint;
ber_type_decoder_f MessageType_decode_ber;
der_type_encoder_f MessageType_encode_der;
xer_type_decoder_f MessageType_decode_xer;
xer_type_encoder_f MessageType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageType_H_ */
#include <asn_internal.h>
