/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_MessageDescriptionInformation_H_
#define	_MessageDescriptionInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MessageDescriptionCode.h"
#include "MessageDescription.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MessageDescriptionInformation */
typedef struct MessageDescriptionInformation {
	MessageDescriptionCode_t	*messageDescriptionCode	/* OPTIONAL */;
	MessageDescription_t	*messageDescription	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageDescriptionInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageDescriptionInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageDescriptionInformation_H_ */
#include <asn_internal.h>
