/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_MessagingEvent_H_
#define	_MessagingEvent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MessagingEventService.h"
#include "RapFileSequenceNumber.h"
#include "SimToolkitIndicator.h"
#include "EventReference.h"
#include "LocationArea.h"
#include "CellId.h"
#include "ExchangeRateCode.h"
#include "Charge.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargedParty;
struct GeographicalLocation;
struct RecEntityCodeList;
struct NetworkElementList;
struct DateTime;
struct NonChargedParty;
struct CallTypeGroup;
struct TaxInformationList;
struct OperatorSpecInfoList;

/* MessagingEvent */
typedef struct MessagingEvent {
	MessagingEventService_t	*messagingEventService	/* OPTIONAL */;
	struct ChargedParty	*chargedParty	/* OPTIONAL */;
	RapFileSequenceNumber_t	*rapFileSequenceNumber	/* OPTIONAL */;
	SimToolkitIndicator_t	*simToolkitIndicator	/* OPTIONAL */;
	struct GeographicalLocation	*geographicalLocation	/* OPTIONAL */;
	EventReference_t	*eventReference	/* OPTIONAL */;
	struct RecEntityCodeList	*recEntityCodeList	/* OPTIONAL */;
	struct NetworkElementList	*networkElementList	/* OPTIONAL */;
	LocationArea_t	*locationArea	/* OPTIONAL */;
	CellId_t	*cellId	/* OPTIONAL */;
	struct DateTime	*serviceStartTimestamp	/* OPTIONAL */;
	struct NonChargedParty	*nonChargedParty	/* OPTIONAL */;
	ExchangeRateCode_t	*exchangeRateCode	/* OPTIONAL */;
	struct CallTypeGroup	*callTypeGroup	/* OPTIONAL */;
	Charge_t	*charge	/* OPTIONAL */;
	struct TaxInformationList	*taxInformationList	/* OPTIONAL */;
	struct OperatorSpecInfoList	*operatorSpecInformation	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessagingEvent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessagingEvent;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargedParty.h"
#include "GeographicalLocation.h"
#include "RecEntityCodeList.h"
#include "NetworkElementList.h"
#include "ServiceStartTimestamp.h"
#include "NonChargedParty.h"
#include "CallTypeGroup.h"
#include "TaxInformationList.h"
#include "OperatorSpecInfoList.h"

#endif	/* _MessagingEvent_H_ */
#include <asn_internal.h>
