/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_OperatorSpecList_H_
#define	_OperatorSpecList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OperatorSpecInformation.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OperatorSpecList */
typedef struct OperatorSpecList {
	A_SEQUENCE_OF(OperatorSpecInformation_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OperatorSpecList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OperatorSpecList;

#ifdef __cplusplus
}
#endif

#endif	/* _OperatorSpecList_H_ */
#include <asn_internal.h>
