/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_PathItemId_H_
#define	_PathItemId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PathItemId */
typedef long	 PathItemId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathItemId;
asn_struct_free_f PathItemId_free;
asn_struct_print_f PathItemId_print;
asn_constr_check_f PathItemId_constraint;
ber_type_decoder_f PathItemId_decode_ber;
der_type_encoder_f PathItemId_encode_der;
xer_type_decoder_f PathItemId_decode_xer;
xer_type_encoder_f PathItemId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PathItemId_H_ */
#include <asn_internal.h>
