/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#include "RapAuditControlInfo.h"

static asn_TYPE_member_t asn_MBR_RapAuditControlInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RapAuditControlInfo, totalSevereReturnValue),
		(ASN_TAG_CLASS_APPLICATION | (533 << 2)),
		0,
		&asn_DEF_TotalSevereReturnValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"totalSevereReturnValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RapAuditControlInfo, returnDetailsCount),
		(ASN_TAG_CLASS_APPLICATION | (528 << 2)),
		0,
		&asn_DEF_ReturnDetailsCount,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"returnDetailsCount"
		},
	{ ATF_POINTER, 2, offsetof(struct RapAuditControlInfo, operatorSpecList),
		(ASN_TAG_CLASS_APPLICATION | (551 << 2)),
		0,
		&asn_DEF_OperatorSpecList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operatorSpecList"
		},
	{ ATF_POINTER, 1, offsetof(struct RapAuditControlInfo, totalSevereReturnTax),
		(ASN_TAG_CLASS_APPLICATION | (553 << 2)),
		0,
		&asn_DEF_TotalSevereReturnTax,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"totalSevereReturnTax"
		},
};
static ber_tlv_tag_t asn_DEF_RapAuditControlInfo_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (541 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RapAuditControlInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (528 << 2)), 1, 0, 0 }, /* returnDetailsCount */
    { (ASN_TAG_CLASS_APPLICATION | (533 << 2)), 0, 0, 0 }, /* totalSevereReturnValue */
    { (ASN_TAG_CLASS_APPLICATION | (551 << 2)), 2, 0, 0 }, /* operatorSpecList */
    { (ASN_TAG_CLASS_APPLICATION | (553 << 2)), 3, 0, 0 } /* totalSevereReturnTax */
};
static asn_SEQUENCE_specifics_t asn_SPC_RapAuditControlInfo_specs_1 = {
	sizeof(struct RapAuditControlInfo),
	offsetof(struct RapAuditControlInfo, _asn_ctx),
	asn_MAP_RapAuditControlInfo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RapAuditControlInfo = {
	"RapAuditControlInfo",
	"RapAuditControlInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RapAuditControlInfo_tags_1,
	sizeof(asn_DEF_RapAuditControlInfo_tags_1)
		/sizeof(asn_DEF_RapAuditControlInfo_tags_1[0]) - 1, /* 1 */
	asn_DEF_RapAuditControlInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_RapAuditControlInfo_tags_1)
		/sizeof(asn_DEF_RapAuditControlInfo_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_RapAuditControlInfo_1,
	4,	/* Elements count */
	&asn_SPC_RapAuditControlInfo_specs_1	/* Additional specs */
};

