/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_RapFileAvailableTimeStamp_H_
#define	_RapFileAvailableTimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DateTimeLong.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RapFileAvailableTimeStamp */
typedef DateTimeLong_t	 RapFileAvailableTimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RapFileAvailableTimeStamp;
asn_struct_free_f RapFileAvailableTimeStamp_free;
asn_struct_print_f RapFileAvailableTimeStamp_print;
asn_constr_check_f RapFileAvailableTimeStamp_constraint;
ber_type_decoder_f RapFileAvailableTimeStamp_decode_ber;
der_type_encoder_f RapFileAvailableTimeStamp_encode_der;
xer_type_decoder_f RapFileAvailableTimeStamp_decode_xer;
xer_type_encoder_f RapFileAvailableTimeStamp_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RapFileAvailableTimeStamp_H_ */
#include <asn_internal.h>
