/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#include "ReturnBatch.h"

static asn_TYPE_member_t asn_MBR_ReturnBatch_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReturnBatch, rapBatchControlInfoRap),
		(ASN_TAG_CLASS_APPLICATION | (537 << 2)),
		0,
		&asn_DEF_RapBatchControlInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rapBatchControlInfoRap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReturnBatch, returnDetails),
		(ASN_TAG_CLASS_APPLICATION | (536 << 2)),
		0,
		&asn_DEF_ReturnDetailList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"returnDetails"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReturnBatch, rapAuditControlInfo),
		(ASN_TAG_CLASS_APPLICATION | (541 << 2)),
		0,
		&asn_DEF_RapAuditControlInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rapAuditControlInfo"
		},
};
static ber_tlv_tag_t asn_DEF_ReturnBatch_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (534 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ReturnBatch_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (536 << 2)), 1, 0, 0 }, /* returnDetails */
    { (ASN_TAG_CLASS_APPLICATION | (537 << 2)), 0, 0, 0 }, /* rapBatchControlInfoRap */
    { (ASN_TAG_CLASS_APPLICATION | (541 << 2)), 2, 0, 0 } /* rapAuditControlInfo */
};
static asn_SEQUENCE_specifics_t asn_SPC_ReturnBatch_specs_1 = {
	sizeof(struct ReturnBatch),
	offsetof(struct ReturnBatch, _asn_ctx),
	asn_MAP_ReturnBatch_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ReturnBatch = {
	"ReturnBatch",
	"ReturnBatch",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ReturnBatch_tags_1,
	sizeof(asn_DEF_ReturnBatch_tags_1)
		/sizeof(asn_DEF_ReturnBatch_tags_1[0]) - 1, /* 1 */
	asn_DEF_ReturnBatch_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReturnBatch_tags_1)
		/sizeof(asn_DEF_ReturnBatch_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ReturnBatch_1,
	3,	/* Elements count */
	&asn_SPC_ReturnBatch_specs_1	/* Additional specs */
};

