/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#include "SevereReturn.h"

static asn_TYPE_member_t asn_MBR_SevereReturn_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SevereReturn, fileSequenceNumber),
		(ASN_TAG_CLASS_APPLICATION | (109 << 2)),
		0,
		&asn_DEF_FileSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fileSequenceNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SevereReturn, callEventDetail),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_CallEventDetail,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callEventDetail"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SevereReturn, errorDetail),
		(ASN_TAG_CLASS_APPLICATION | (520 << 2)),
		0,
		&asn_DEF_ErrorDetailList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"errorDetail"
		},
	{ ATF_POINTER, 1, offsetof(struct SevereReturn, operatorSpecList),
		(ASN_TAG_CLASS_APPLICATION | (551 << 2)),
		0,
		&asn_DEF_OperatorSpecList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operatorSpecList"
		},
};
static ber_tlv_tag_t asn_DEF_SevereReturn_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (540 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SevereReturn_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (9 << 2)), 1, 0, 0 }, /* mobileOriginatedCall */
    { (ASN_TAG_CLASS_APPLICATION | (10 << 2)), 1, 0, 0 }, /* mobileTerminatedCall */
    { (ASN_TAG_CLASS_APPLICATION | (11 << 2)), 1, 0, 0 }, /* supplServiceEvent */
    { (ASN_TAG_CLASS_APPLICATION | (12 << 2)), 1, 0, 0 }, /* serviceCentreUsage */
    { (ASN_TAG_CLASS_APPLICATION | (14 << 2)), 1, 0, 0 }, /* gprsCall */
    { (ASN_TAG_CLASS_APPLICATION | (17 << 2)), 1, 0, 0 }, /* contentTransaction */
    { (ASN_TAG_CLASS_APPLICATION | (109 << 2)), 0, 0, 0 }, /* fileSequenceNumber */
    { (ASN_TAG_CLASS_APPLICATION | (297 << 2)), 1, 0, 0 }, /* locationService */
    { (ASN_TAG_CLASS_APPLICATION | (433 << 2)), 1, 0, 0 }, /* messagingEvent */
    { (ASN_TAG_CLASS_APPLICATION | (434 << 2)), 1, 0, 0 }, /* mobileSession */
    { (ASN_TAG_CLASS_APPLICATION | (520 << 2)), 2, 0, 0 }, /* errorDetail */
    { (ASN_TAG_CLASS_APPLICATION | (551 << 2)), 3, 0, 0 } /* operatorSpecList */
};
static asn_SEQUENCE_specifics_t asn_SPC_SevereReturn_specs_1 = {
	sizeof(struct SevereReturn),
	offsetof(struct SevereReturn, _asn_ctx),
	asn_MAP_SevereReturn_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SevereReturn = {
	"SevereReturn",
	"SevereReturn",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SevereReturn_tags_1,
	sizeof(asn_DEF_SevereReturn_tags_1)
		/sizeof(asn_DEF_SevereReturn_tags_1[0]) - 1, /* 1 */
	asn_DEF_SevereReturn_tags_1,	/* Same as above */
	sizeof(asn_DEF_SevereReturn_tags_1)
		/sizeof(asn_DEF_SevereReturn_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_SevereReturn_1,
	4,	/* Elements count */
	&asn_SPC_SevereReturn_specs_1	/* Additional specs */
};

