/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_SpecificationVersionNumber_H_
#define	_SpecificationVersionNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SpecificationVersionNumber */
typedef long	 SpecificationVersionNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpecificationVersionNumber;
asn_struct_free_f SpecificationVersionNumber_free;
asn_struct_print_f SpecificationVersionNumber_print;
asn_constr_check_f SpecificationVersionNumber_constraint;
ber_type_decoder_f SpecificationVersionNumber_decode_ber;
der_type_encoder_f SpecificationVersionNumber_encode_der;
xer_type_decoder_f SpecificationVersionNumber_decode_xer;
xer_type_encoder_f SpecificationVersionNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SpecificationVersionNumber_H_ */
#include <asn_internal.h>
