/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_SupplServiceActionCode_H_
#define	_SupplServiceActionCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SupplServiceActionCode */
typedef long	 SupplServiceActionCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupplServiceActionCode;
asn_struct_free_f SupplServiceActionCode_free;
asn_struct_print_f SupplServiceActionCode_print;
asn_constr_check_f SupplServiceActionCode_constraint;
ber_type_decoder_f SupplServiceActionCode_decode_ber;
der_type_encoder_f SupplServiceActionCode_encode_der;
xer_type_decoder_f SupplServiceActionCode_decode_xer;
xer_type_encoder_f SupplServiceActionCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SupplServiceActionCode_H_ */
#include <asn_internal.h>
