/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_TransferBatch_H_
#define	_TransferBatch_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BatchControlInfo;
struct AccountingInfo;
struct NetworkInfo;
struct CallEventDetailList;
struct AuditControlInfo;

/* TransferBatch */
typedef struct TransferBatch {
	struct BatchControlInfo	*batchControlInfo	/* OPTIONAL */;
	struct AccountingInfo	*accountingInfo	/* OPTIONAL */;
	struct NetworkInfo	*networkInfo	/* OPTIONAL */;
	struct CallEventDetailList	*callEventDetails	/* OPTIONAL */;
	struct AuditControlInfo	*auditControlInfo	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransferBatch_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransferBatch;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BatchControlInfo.h"
#include "AccountingInfo.h"
#include "NetworkInfo.h"
#include "CallEventDetailList.h"
#include "AuditControlInfo.h"

#endif	/* _TransferBatch_H_ */
#include <asn_internal.h>
