/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_TransactionAuthCode_H_
#define	_TransactionAuthCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TransactionAuthCode */
typedef AsciiString_t	 TransactionAuthCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransactionAuthCode;
asn_struct_free_f TransactionAuthCode_free;
asn_struct_print_f TransactionAuthCode_print;
asn_constr_check_f TransactionAuthCode_constraint;
ber_type_decoder_f TransactionAuthCode_decode_ber;
der_type_encoder_f TransactionAuthCode_encode_der;
xer_type_decoder_f TransactionAuthCode_decode_xer;
xer_type_encoder_f TransactionAuthCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TransactionAuthCode_H_ */
#include <asn_internal.h>
