/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_UtcTimeOffsetInfo_H_
#define	_UtcTimeOffsetInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UtcTimeOffsetCode.h"
#include "UtcTimeOffset.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UtcTimeOffsetInfo */
typedef struct UtcTimeOffsetInfo {
	UtcTimeOffsetCode_t	*utcTimeOffsetCode	/* OPTIONAL */;
	UtcTimeOffset_t	*utcTimeOffset	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UtcTimeOffsetInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UtcTimeOffsetInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _UtcTimeOffsetInfo_H_ */
#include <asn_internal.h>
