/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_UtcTimeOffset_H_
#define	_UtcTimeOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UtcTimeOffset */
typedef AsciiString_t	 UtcTimeOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UtcTimeOffset;
asn_struct_free_f UtcTimeOffset_free;
asn_struct_print_f UtcTimeOffset_print;
asn_constr_check_f UtcTimeOffset_constraint;
ber_type_decoder_f UtcTimeOffset_decode_ber;
der_type_encoder_f UtcTimeOffset_encode_der;
xer_type_decoder_f UtcTimeOffset_decode_xer;
xer_type_encoder_f UtcTimeOffset_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UtcTimeOffset_H_ */
#include <asn_internal.h>
