/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_AccessPointNameNI_H_
#define	_AccessPointNameNI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AccessPointNameNI */
typedef AsciiString_t	 AccessPointNameNI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccessPointNameNI;
asn_struct_free_f AccessPointNameNI_free;
asn_struct_print_f AccessPointNameNI_print;
asn_constr_check_f AccessPointNameNI_constraint;
ber_type_decoder_f AccessPointNameNI_decode_ber;
der_type_encoder_f AccessPointNameNI_encode_der;
xer_type_decoder_f AccessPointNameNI_decode_xer;
xer_type_encoder_f AccessPointNameNI_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AccessPointNameNI_H_ */
#include <asn_internal.h>
