/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_AgeOfLocation_H_
#define	_AgeOfLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AgeOfLocation */
typedef long	 AgeOfLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AgeOfLocation;
asn_struct_free_f AgeOfLocation_free;
asn_struct_print_f AgeOfLocation_print;
asn_constr_check_f AgeOfLocation_constraint;
ber_type_decoder_f AgeOfLocation_decode_ber;
der_type_encoder_f AgeOfLocation_encode_der;
xer_type_decoder_f AgeOfLocation_decode_xer;
xer_type_encoder_f AgeOfLocation_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AgeOfLocation_H_ */
#include <asn_internal.h>
