/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_CallTypeLevel3_H_
#define	_CallTypeLevel3_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CallTypeLevel3 */
typedef long	 CallTypeLevel3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallTypeLevel3;
asn_struct_free_f CallTypeLevel3_free;
asn_struct_print_f CallTypeLevel3_print;
asn_constr_check_f CallTypeLevel3_constraint;
ber_type_decoder_f CallTypeLevel3_decode_ber;
der_type_encoder_f CallTypeLevel3_encode_der;
xer_type_decoder_f CallTypeLevel3_decode_xer;
xer_type_encoder_f CallTypeLevel3_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallTypeLevel3_H_ */
#include <asn_internal.h>
