/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_CalledRegion_H_
#define	_CalledRegion_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CalledRegion */
typedef AsciiString_t	 CalledRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CalledRegion;
asn_struct_free_f CalledRegion_free;
asn_struct_print_f CalledRegion_print;
asn_constr_check_f CalledRegion_constraint;
ber_type_decoder_f CalledRegion_decode_ber;
der_type_encoder_f CalledRegion_encode_der;
xer_type_decoder_f CalledRegion_decode_xer;
xer_type_encoder_f CalledRegion_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CalledRegion_H_ */
#include <asn_internal.h>
