/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "CamelServiceUsed.h"

static asn_TYPE_member_t asn_MBR_CamelServiceUsed_1[] = {
	{ ATF_POINTER, 9, offsetof(struct CamelServiceUsed, camelServiceLevel),
		(ASN_TAG_CLASS_APPLICATION | (56 << 2)),
		0,
		&asn_DEF_CamelServiceLevel,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"camelServiceLevel"
		},
	{ ATF_POINTER, 8, offsetof(struct CamelServiceUsed, camelServiceKey),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		0,
		&asn_DEF_CamelServiceKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"camelServiceKey"
		},
	{ ATF_POINTER, 7, offsetof(struct CamelServiceUsed, defaultCallHandling),
		(ASN_TAG_CLASS_APPLICATION | (87 << 2)),
		0,
		&asn_DEF_DefaultCallHandlingIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"defaultCallHandling"
		},
	{ ATF_POINTER, 6, offsetof(struct CamelServiceUsed, exchangeRateCode),
		(ASN_TAG_CLASS_APPLICATION | (105 << 2)),
		0,
		&asn_DEF_ExchangeRateCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"exchangeRateCode"
		},
	{ ATF_POINTER, 5, offsetof(struct CamelServiceUsed, taxInformation),
		(ASN_TAG_CLASS_APPLICATION | (214 << 2)),
		0,
		&asn_DEF_TaxInformationList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"taxInformation"
		},
	{ ATF_POINTER, 4, offsetof(struct CamelServiceUsed, discountInformation),
		(ASN_TAG_CLASS_APPLICATION | (96 << 2)),
		0,
		&asn_DEF_DiscountInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"discountInformation"
		},
	{ ATF_POINTER, 3, offsetof(struct CamelServiceUsed, camelInvocationFee),
		(ASN_TAG_CLASS_APPLICATION | (422 << 2)),
		0,
		&asn_DEF_CamelInvocationFee,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"camelInvocationFee"
		},
	{ ATF_POINTER, 2, offsetof(struct CamelServiceUsed, threeGcamelDestination),
		(ASN_TAG_CLASS_APPLICATION | (431 << 2)),
		0,
		&asn_DEF_ThreeGcamelDestination,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"threeGcamelDestination"
		},
	{ ATF_POINTER, 1, offsetof(struct CamelServiceUsed, cseInformation),
		(ASN_TAG_CLASS_APPLICATION | (79 << 2)),
		0,
		&asn_DEF_CseInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cseInformation"
		},
};
static ber_tlv_tag_t asn_DEF_CamelServiceUsed_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (57 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CamelServiceUsed_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 1, 0, 0 }, /* camelServiceKey */
    { (ASN_TAG_CLASS_APPLICATION | (56 << 2)), 0, 0, 0 }, /* camelServiceLevel */
    { (ASN_TAG_CLASS_APPLICATION | (79 << 2)), 8, 0, 0 }, /* cseInformation */
    { (ASN_TAG_CLASS_APPLICATION | (87 << 2)), 2, 0, 0 }, /* defaultCallHandling */
    { (ASN_TAG_CLASS_APPLICATION | (96 << 2)), 5, 0, 0 }, /* discountInformation */
    { (ASN_TAG_CLASS_APPLICATION | (105 << 2)), 3, 0, 0 }, /* exchangeRateCode */
    { (ASN_TAG_CLASS_APPLICATION | (214 << 2)), 4, 0, 0 }, /* taxInformation */
    { (ASN_TAG_CLASS_APPLICATION | (422 << 2)), 6, 0, 0 }, /* camelInvocationFee */
    { (ASN_TAG_CLASS_APPLICATION | (431 << 2)), 7, 0, 0 } /* threeGcamelDestination */
};
static asn_SEQUENCE_specifics_t asn_SPC_CamelServiceUsed_specs_1 = {
	sizeof(struct CamelServiceUsed),
	offsetof(struct CamelServiceUsed, _asn_ctx),
	asn_MAP_CamelServiceUsed_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	8,	/* Start extensions */
	10	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CamelServiceUsed = {
	"CamelServiceUsed",
	"CamelServiceUsed",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CamelServiceUsed_tags_1,
	sizeof(asn_DEF_CamelServiceUsed_tags_1)
		/sizeof(asn_DEF_CamelServiceUsed_tags_1[0]) - 1, /* 1 */
	asn_DEF_CamelServiceUsed_tags_1,	/* Same as above */
	sizeof(asn_DEF_CamelServiceUsed_tags_1)
		/sizeof(asn_DEF_CamelServiceUsed_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_CamelServiceUsed_1,
	9,	/* Elements count */
	&asn_SPC_CamelServiceUsed_specs_1	/* Additional specs */
};

