/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ChargingTimeStamp_H_
#define	_ChargingTimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DateTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ChargingTimeStamp */
typedef DateTime_t	 ChargingTimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargingTimeStamp;
asn_struct_free_f ChargingTimeStamp_free;
asn_struct_print_f ChargingTimeStamp_print;
asn_constr_check_f ChargingTimeStamp_constraint;
ber_type_decoder_f ChargingTimeStamp_decode_ber;
der_type_encoder_f ChargingTimeStamp_encode_der;
xer_type_decoder_f ChargingTimeStamp_decode_xer;
xer_type_encoder_f ChargingTimeStamp_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChargingTimeStamp_H_ */
#include <asn_internal.h>
