/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ChargeDetailTimeStamp_H_
#define	_ChargeDetailTimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChargingTimeStamp.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ChargeDetailTimeStamp */
typedef ChargingTimeStamp_t	 ChargeDetailTimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargeDetailTimeStamp;
asn_struct_free_f ChargeDetailTimeStamp_free;
asn_struct_print_f ChargeDetailTimeStamp_print;
asn_constr_check_f ChargeDetailTimeStamp_constraint;
ber_type_decoder_f ChargeDetailTimeStamp_decode_ber;
der_type_encoder_f ChargeDetailTimeStamp_encode_der;
xer_type_decoder_f ChargeDetailTimeStamp_decode_xer;
xer_type_encoder_f ChargeDetailTimeStamp_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChargeDetailTimeStamp_H_ */
#include <asn_internal.h>
