/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ChargedPartyIdentification_H_
#define	_ChargedPartyIdentification_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChargedPartyIdType.h"
#include "ChargedPartyIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChargedPartyIdentification */
typedef struct ChargedPartyIdentification {
	ChargedPartyIdType_t	*chargedPartyIdType	/* OPTIONAL */;
	ChargedPartyIdentifier_t	*chargedPartyIdentifier	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChargedPartyIdentification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargedPartyIdentification;

#ifdef __cplusplus
}
#endif

#endif	/* _ChargedPartyIdentification_H_ */
#include <asn_internal.h>
