/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ChargedPartyIdentifier_H_
#define	_ChargedPartyIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ChargedPartyIdentifier */
typedef AsciiString_t	 ChargedPartyIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargedPartyIdentifier;
asn_struct_free_f ChargedPartyIdentifier_free;
asn_struct_print_f ChargedPartyIdentifier_print;
asn_constr_check_f ChargedPartyIdentifier_constraint;
ber_type_decoder_f ChargedPartyIdentifier_decode_ber;
der_type_encoder_f ChargedPartyIdentifier_encode_der;
xer_type_decoder_f ChargedPartyIdentifier_decode_xer;
xer_type_encoder_f ChargedPartyIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChargedPartyIdentifier_H_ */
#include <asn_internal.h>
