/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ContentProviderName_H_
#define	_ContentProviderName_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ContentProviderName */
typedef AsciiString_t	 ContentProviderName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContentProviderName;
asn_struct_free_f ContentProviderName_free;
asn_struct_print_f ContentProviderName_print;
asn_constr_check_f ContentProviderName_constraint;
ber_type_decoder_f ContentProviderName_decode_ber;
der_type_encoder_f ContentProviderName_encode_der;
xer_type_decoder_f ContentProviderName_decode_xer;
xer_type_encoder_f ContentProviderName_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ContentProviderName_H_ */
#include <asn_internal.h>
