/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_CurrencyConversion_H_
#define	_CurrencyConversion_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExchangeRateCode.h"
#include "NumberOfDecimalPlaces.h"
#include "ExchangeRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CurrencyConversion */
typedef struct CurrencyConversion {
	ExchangeRateCode_t	*exchangeRateCode	/* OPTIONAL */;
	NumberOfDecimalPlaces_t	*numberOfDecimalPlaces	/* OPTIONAL */;
	ExchangeRate_t	*exchangeRate	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CurrencyConversion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurrencyConversion;

#ifdef __cplusplus
}
#endif

#endif	/* _CurrencyConversion_H_ */
#include <asn_internal.h>
