/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_DefaultCallHandlingIndicator_H_
#define	_DefaultCallHandlingIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DefaultCallHandlingIndicator */
typedef long	 DefaultCallHandlingIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefaultCallHandlingIndicator;
asn_struct_free_f DefaultCallHandlingIndicator_free;
asn_struct_print_f DefaultCallHandlingIndicator_print;
asn_constr_check_f DefaultCallHandlingIndicator_constraint;
ber_type_decoder_f DefaultCallHandlingIndicator_decode_ber;
der_type_encoder_f DefaultCallHandlingIndicator_encode_der;
xer_type_decoder_f DefaultCallHandlingIndicator_decode_xer;
xer_type_encoder_f DefaultCallHandlingIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DefaultCallHandlingIndicator_H_ */
#include <asn_internal.h>
