/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_DepositTimeStamp_H_
#define	_DepositTimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DateTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DepositTimeStamp */
typedef DateTime_t	 DepositTimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DepositTimeStamp;
asn_struct_free_f DepositTimeStamp_free;
asn_struct_print_f DepositTimeStamp_print;
asn_constr_check_f DepositTimeStamp_constraint;
ber_type_decoder_f DepositTimeStamp_decode_ber;
der_type_encoder_f DepositTimeStamp_encode_der;
xer_type_decoder_f DepositTimeStamp_decode_xer;
xer_type_encoder_f DepositTimeStamp_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DepositTimeStamp_H_ */
#include <asn_internal.h>
