/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_DialledDigits_H_
#define	_DialledDigits_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DialledDigits */
typedef AsciiString_t	 DialledDigits_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DialledDigits;
asn_struct_free_f DialledDigits_free;
asn_struct_print_f DialledDigits_print;
asn_constr_check_f DialledDigits_constraint;
ber_type_decoder_f DialledDigits_decode_ber;
der_type_encoder_f DialledDigits_encode_der;
xer_type_decoder_f DialledDigits_decode_xer;
xer_type_encoder_f DialledDigits_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DialledDigits_H_ */
#include <asn_internal.h>
