/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_DiscountableAmount_H_
#define	_DiscountableAmount_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AbsoluteAmount.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DiscountableAmount */
typedef AbsoluteAmount_t	 DiscountableAmount_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiscountableAmount;
asn_struct_free_f DiscountableAmount_free;
asn_struct_print_f DiscountableAmount_print;
asn_constr_check_f DiscountableAmount_constraint;
ber_type_decoder_f DiscountableAmount_decode_ber;
der_type_encoder_f DiscountableAmount_encode_der;
xer_type_decoder_f DiscountableAmount_decode_xer;
xer_type_encoder_f DiscountableAmount_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DiscountableAmount_H_ */
#include <asn_internal.h>
