/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "DiscountInformation.h"

static asn_TYPE_member_t asn_MBR_DiscountInformation_1[] = {
	{ ATF_POINTER, 3, offsetof(struct DiscountInformation, discountCode),
		(ASN_TAG_CLASS_APPLICATION | (91 << 2)),
		0,
		&asn_DEF_DiscountCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"discountCode"
		},
	{ ATF_POINTER, 2, offsetof(struct DiscountInformation, discount),
		(ASN_TAG_CLASS_APPLICATION | (412 << 2)),
		0,
		&asn_DEF_Discount,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"discount"
		},
	{ ATF_POINTER, 1, offsetof(struct DiscountInformation, discountableAmount),
		(ASN_TAG_CLASS_APPLICATION | (423 << 2)),
		0,
		&asn_DEF_DiscountableAmount,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"discountableAmount"
		},
};
static ber_tlv_tag_t asn_DEF_DiscountInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (96 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DiscountInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (91 << 2)), 0, 0, 0 }, /* discountCode */
    { (ASN_TAG_CLASS_APPLICATION | (412 << 2)), 1, 0, 0 }, /* discount */
    { (ASN_TAG_CLASS_APPLICATION | (423 << 2)), 2, 0, 0 } /* discountableAmount */
};
static asn_SEQUENCE_specifics_t asn_SPC_DiscountInformation_specs_1 = {
	sizeof(struct DiscountInformation),
	offsetof(struct DiscountInformation, _asn_ctx),
	asn_MAP_DiscountInformation_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DiscountInformation = {
	"DiscountInformation",
	"DiscountInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DiscountInformation_tags_1,
	sizeof(asn_DEF_DiscountInformation_tags_1)
		/sizeof(asn_DEF_DiscountInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_DiscountInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_DiscountInformation_tags_1)
		/sizeof(asn_DEF_DiscountInformation_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_DiscountInformation_1,
	3,	/* Elements count */
	&asn_SPC_DiscountInformation_specs_1	/* Additional specs */
};

