/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_Esn_H_
#define	_Esn_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NumberString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Esn */
typedef NumberString_t	 Esn_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Esn;
asn_struct_free_f Esn_free;
asn_struct_print_f Esn_print;
asn_constr_check_f Esn_constraint;
ber_type_decoder_f Esn_decode_ber;
der_type_encoder_f Esn_encode_der;
xer_type_decoder_f Esn_decode_xer;
xer_type_encoder_f Esn_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Esn_H_ */
#include <asn_internal.h>
