/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ExchangeRate_H_
#define	_ExchangeRate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExchangeRate */
typedef long	 ExchangeRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExchangeRate;
asn_struct_free_f ExchangeRate_free;
asn_struct_print_f ExchangeRate_print;
asn_constr_check_f ExchangeRate_constraint;
ber_type_decoder_f ExchangeRate_decode_ber;
der_type_encoder_f ExchangeRate_encode_der;
xer_type_decoder_f ExchangeRate_decode_xer;
xer_type_encoder_f ExchangeRate_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ExchangeRate_H_ */
#include <asn_internal.h>
