/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "GeographicalLocation.h"

static asn_TYPE_member_t asn_MBR_GeographicalLocation_1[] = {
	{ ATF_POINTER, 3, offsetof(struct GeographicalLocation, servingNetwork),
		(ASN_TAG_CLASS_APPLICATION | (195 << 2)),
		0,
		&asn_DEF_ServingNetwork,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servingNetwork"
		},
	{ ATF_POINTER, 2, offsetof(struct GeographicalLocation, servingBid),
		(ASN_TAG_CLASS_APPLICATION | (198 << 2)),
		0,
		&asn_DEF_ServingBid,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servingBid"
		},
	{ ATF_POINTER, 1, offsetof(struct GeographicalLocation, servingLocationDescription),
		(ASN_TAG_CLASS_APPLICATION | (414 << 2)),
		0,
		&asn_DEF_ServingLocationDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servingLocationDescription"
		},
};
static ber_tlv_tag_t asn_DEF_GeographicalLocation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (113 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GeographicalLocation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (195 << 2)), 0, 0, 0 }, /* servingNetwork */
    { (ASN_TAG_CLASS_APPLICATION | (198 << 2)), 1, 0, 0 }, /* servingBid */
    { (ASN_TAG_CLASS_APPLICATION | (414 << 2)), 2, 0, 0 } /* servingLocationDescription */
};
static asn_SEQUENCE_specifics_t asn_SPC_GeographicalLocation_specs_1 = {
	sizeof(struct GeographicalLocation),
	offsetof(struct GeographicalLocation, _asn_ctx),
	asn_MAP_GeographicalLocation_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GeographicalLocation = {
	"GeographicalLocation",
	"GeographicalLocation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GeographicalLocation_tags_1,
	sizeof(asn_DEF_GeographicalLocation_tags_1)
		/sizeof(asn_DEF_GeographicalLocation_tags_1[0]) - 1, /* 1 */
	asn_DEF_GeographicalLocation_tags_1,	/* Same as above */
	sizeof(asn_DEF_GeographicalLocation_tags_1)
		/sizeof(asn_DEF_GeographicalLocation_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_GeographicalLocation_1,
	3,	/* Elements count */
	&asn_SPC_GeographicalLocation_specs_1	/* Additional specs */
};

