/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "GprsBasicCallInformation.h"

static asn_TYPE_member_t asn_MBR_GprsBasicCallInformation_1[] = {
	{ ATF_POINTER, 10, offsetof(struct GprsBasicCallInformation, gprsChargeableSubscriber),
		(ASN_TAG_CLASS_APPLICATION | (115 << 2)),
		0,
		&asn_DEF_GprsChargeableSubscriber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gprsChargeableSubscriber"
		},
	{ ATF_POINTER, 9, offsetof(struct GprsBasicCallInformation, rapFileSequenceNumber),
		(ASN_TAG_CLASS_APPLICATION | (181 << 2)),
		0,
		&asn_DEF_RapFileSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rapFileSequenceNumber"
		},
	{ ATF_POINTER, 8, offsetof(struct GprsBasicCallInformation, gprsDestination),
		(ASN_TAG_CLASS_APPLICATION | (116 << 2)),
		0,
		&asn_DEF_GprsDestination,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gprsDestination"
		},
	{ ATF_POINTER, 7, offsetof(struct GprsBasicCallInformation, callEventStartTimeStamp),
		(ASN_TAG_CLASS_APPLICATION | (44 << 2)),
		0,
		&asn_DEF_CallEventStartTimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callEventStartTimeStamp"
		},
	{ ATF_POINTER, 6, offsetof(struct GprsBasicCallInformation, totalCallEventDuration),
		(ASN_TAG_CLASS_APPLICATION | (223 << 2)),
		0,
		&asn_DEF_TotalCallEventDuration,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"totalCallEventDuration"
		},
	{ ATF_POINTER, 5, offsetof(struct GprsBasicCallInformation, causeForTerm),
		(ASN_TAG_CLASS_APPLICATION | (58 << 2)),
		0,
		&asn_DEF_CauseForTerm,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"causeForTerm"
		},
	{ ATF_POINTER, 4, offsetof(struct GprsBasicCallInformation, partialTypeIndicator),
		(ASN_TAG_CLASS_APPLICATION | (166 << 2)),
		0,
		&asn_DEF_PartialTypeIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"partialTypeIndicator"
		},
	{ ATF_POINTER, 3, offsetof(struct GprsBasicCallInformation, pDPContextStartTimestamp),
		(ASN_TAG_CLASS_APPLICATION | (260 << 2)),
		0,
		&asn_DEF_PDPContextStartTimestamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pDPContextStartTimestamp"
		},
	{ ATF_POINTER, 2, offsetof(struct GprsBasicCallInformation, networkInitPDPContext),
		(ASN_TAG_CLASS_APPLICATION | (245 << 2)),
		0,
		&asn_DEF_NetworkInitPDPContext,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkInitPDPContext"
		},
	{ ATF_POINTER, 1, offsetof(struct GprsBasicCallInformation, chargingId),
		(ASN_TAG_CLASS_APPLICATION | (72 << 2)),
		0,
		&asn_DEF_ChargingId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargingId"
		},
};
static ber_tlv_tag_t asn_DEF_GprsBasicCallInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (114 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GprsBasicCallInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (44 << 2)), 3, 0, 0 }, /* callEventStartTimeStamp */
    { (ASN_TAG_CLASS_APPLICATION | (58 << 2)), 5, 0, 0 }, /* causeForTerm */
    { (ASN_TAG_CLASS_APPLICATION | (72 << 2)), 9, 0, 0 }, /* chargingId */
    { (ASN_TAG_CLASS_APPLICATION | (115 << 2)), 0, 0, 0 }, /* gprsChargeableSubscriber */
    { (ASN_TAG_CLASS_APPLICATION | (116 << 2)), 2, 0, 0 }, /* gprsDestination */
    { (ASN_TAG_CLASS_APPLICATION | (166 << 2)), 6, 0, 0 }, /* partialTypeIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (181 << 2)), 1, 0, 0 }, /* rapFileSequenceNumber */
    { (ASN_TAG_CLASS_APPLICATION | (223 << 2)), 4, 0, 0 }, /* totalCallEventDuration */
    { (ASN_TAG_CLASS_APPLICATION | (245 << 2)), 8, 0, 0 }, /* networkInitPDPContext */
    { (ASN_TAG_CLASS_APPLICATION | (260 << 2)), 7, 0, 0 } /* pDPContextStartTimestamp */
};
static asn_SEQUENCE_specifics_t asn_SPC_GprsBasicCallInformation_specs_1 = {
	sizeof(struct GprsBasicCallInformation),
	offsetof(struct GprsBasicCallInformation, _asn_ctx),
	asn_MAP_GprsBasicCallInformation_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	9,	/* Start extensions */
	11	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GprsBasicCallInformation = {
	"GprsBasicCallInformation",
	"GprsBasicCallInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GprsBasicCallInformation_tags_1,
	sizeof(asn_DEF_GprsBasicCallInformation_tags_1)
		/sizeof(asn_DEF_GprsBasicCallInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_GprsBasicCallInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_GprsBasicCallInformation_tags_1)
		/sizeof(asn_DEF_GprsBasicCallInformation_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_GprsBasicCallInformation_1,
	10,	/* Elements count */
	&asn_SPC_GprsBasicCallInformation_specs_1	/* Additional specs */
};

