/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "GprsServiceUsed.h"

static asn_TYPE_member_t asn_MBR_GprsServiceUsed_1[] = {
	{ ATF_POINTER, 4, offsetof(struct GprsServiceUsed, iMSSignallingContext),
		(ASN_TAG_CLASS_APPLICATION | (418 << 2)),
		0,
		&asn_DEF_IMSSignallingContext,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iMSSignallingContext"
		},
	{ ATF_POINTER, 3, offsetof(struct GprsServiceUsed, dataVolumeIncoming),
		(ASN_TAG_CLASS_APPLICATION | (250 << 2)),
		0,
		&asn_DEF_DataVolumeIncoming,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeIncoming"
		},
	{ ATF_POINTER, 2, offsetof(struct GprsServiceUsed, dataVolumeOutgoing),
		(ASN_TAG_CLASS_APPLICATION | (251 << 2)),
		0,
		&asn_DEF_DataVolumeOutgoing,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeOutgoing"
		},
	{ ATF_POINTER, 1, offsetof(struct GprsServiceUsed, chargeInformationList),
		(ASN_TAG_CLASS_APPLICATION | (70 << 2)),
		0,
		&asn_DEF_ChargeInformationList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargeInformationList"
		},
};
static ber_tlv_tag_t asn_DEF_GprsServiceUsed_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (121 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GprsServiceUsed_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (70 << 2)), 3, 0, 0 }, /* chargeInformationList */
    { (ASN_TAG_CLASS_APPLICATION | (250 << 2)), 1, 0, 0 }, /* dataVolumeIncoming */
    { (ASN_TAG_CLASS_APPLICATION | (251 << 2)), 2, 0, 0 }, /* dataVolumeOutgoing */
    { (ASN_TAG_CLASS_APPLICATION | (418 << 2)), 0, 0, 0 } /* iMSSignallingContext */
};
static asn_SEQUENCE_specifics_t asn_SPC_GprsServiceUsed_specs_1 = {
	sizeof(struct GprsServiceUsed),
	offsetof(struct GprsServiceUsed, _asn_ctx),
	asn_MAP_GprsServiceUsed_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GprsServiceUsed = {
	"GprsServiceUsed",
	"GprsServiceUsed",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GprsServiceUsed_tags_1,
	sizeof(asn_DEF_GprsServiceUsed_tags_1)
		/sizeof(asn_DEF_GprsServiceUsed_tags_1[0]) - 1, /* 1 */
	asn_DEF_GprsServiceUsed_tags_1,	/* Same as above */
	sizeof(asn_DEF_GprsServiceUsed_tags_1)
		/sizeof(asn_DEF_GprsServiceUsed_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_GprsServiceUsed_1,
	4,	/* Elements count */
	&asn_SPC_GprsServiceUsed_specs_1	/* Additional specs */
};

