/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_GprsBasicCallInformation_H_
#define	_GprsBasicCallInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RapFileSequenceNumber.h"
#include "TotalCallEventDuration.h"
#include "CauseForTerm.h"
#include "PartialTypeIndicator.h"
#include "NetworkInitPDPContext.h"
#include "ChargingId.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GprsChargeableSubscriber;
struct GprsDestination;
struct DateTime;

/* GprsBasicCallInformation */
typedef struct GprsBasicCallInformation {
	struct GprsChargeableSubscriber	*gprsChargeableSubscriber	/* OPTIONAL */;
	RapFileSequenceNumber_t	*rapFileSequenceNumber	/* OPTIONAL */;
	struct GprsDestination	*gprsDestination	/* OPTIONAL */;
	struct DateTime	*callEventStartTimeStamp	/* OPTIONAL */;
	TotalCallEventDuration_t	*totalCallEventDuration	/* OPTIONAL */;
	CauseForTerm_t	*causeForTerm	/* OPTIONAL */;
	PartialTypeIndicator_t	*partialTypeIndicator	/* OPTIONAL */;
	struct DateTime	*pDPContextStartTimestamp	/* OPTIONAL */;
	NetworkInitPDPContext_t	*networkInitPDPContext	/* OPTIONAL */;
	ChargingId_t	*chargingId	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GprsBasicCallInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GprsBasicCallInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GprsChargeableSubscriber.h"
#include "GprsDestination.h"
#include "CallEventStartTimeStamp.h"
#include "PDPContextStartTimestamp.h"

#endif	/* _GprsBasicCallInformation_H_ */
#include <asn_internal.h>
