/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_GprsDestination_H_
#define	_GprsDestination_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AccessPointNameNI.h"
#include "AccessPointNameOI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GprsDestination */
typedef struct GprsDestination {
	AccessPointNameNI_t	*accessPointNameNI	/* OPTIONAL */;
	AccessPointNameOI_t	*accessPointNameOI	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GprsDestination_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GprsDestination;

#ifdef __cplusplus
}
#endif

#endif	/* _GprsDestination_H_ */
#include <asn_internal.h>
