/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_HorizontalAccuracyRequested_H_
#define	_HorizontalAccuracyRequested_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HorizontalAccuracyRequested */
typedef long	 HorizontalAccuracyRequested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HorizontalAccuracyRequested;
asn_struct_free_f HorizontalAccuracyRequested_free;
asn_struct_print_f HorizontalAccuracyRequested_print;
asn_constr_check_f HorizontalAccuracyRequested_constraint;
ber_type_decoder_f HorizontalAccuracyRequested_decode_ber;
der_type_encoder_f HorizontalAccuracyRequested_encode_der;
xer_type_decoder_f HorizontalAccuracyRequested_decode_xer;
xer_type_encoder_f HorizontalAccuracyRequested_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HorizontalAccuracyRequested_H_ */
#include <asn_internal.h>
