/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_InternetServiceProvider_H_
#define	_InternetServiceProvider_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IspIdType.h"
#include "IspIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InternetServiceProvider */
typedef struct InternetServiceProvider {
	IspIdType_t	*ispIdType	/* OPTIONAL */;
	IspIdentifier_t	*ispIdentifier	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InternetServiceProvider_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InternetServiceProvider;

#ifdef __cplusplus
}
#endif

#endif	/* _InternetServiceProvider_H_ */
#include <asn_internal.h>
