/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_LocationServiceUsage_H_
#define	_LocationServiceUsage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LCSQosRequested;
struct LCSQosDelivered;
struct DateTime;
struct ChargeInformationList;

/* LocationServiceUsage */
typedef struct LocationServiceUsage {
	struct LCSQosRequested	*lCSQosRequested	/* OPTIONAL */;
	struct LCSQosDelivered	*lCSQosDelivered	/* OPTIONAL */;
	struct DateTime	*chargingTimeStamp	/* OPTIONAL */;
	struct ChargeInformationList	*chargeInformationList	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LocationServiceUsage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocationServiceUsage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LCSQosRequested.h"
#include "LCSQosDelivered.h"
#include "ChargingTimeStamp.h"
#include "ChargeInformationList.h"

#endif	/* _LocationServiceUsage_H_ */
#include <asn_internal.h>
