/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_LocationIdentifier_H_
#define	_LocationIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LocationIdentifier */
typedef AsciiString_t	 LocationIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocationIdentifier;
asn_struct_free_f LocationIdentifier_free;
asn_struct_print_f LocationIdentifier_print;
asn_constr_check_f LocationIdentifier_constraint;
ber_type_decoder_f LocationIdentifier_decode_ber;
der_type_encoder_f LocationIdentifier_encode_der;
xer_type_decoder_f LocationIdentifier_decode_xer;
xer_type_encoder_f LocationIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LocationIdentifier_H_ */
#include <asn_internal.h>
