/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_MessageDescriptionCode_H_
#define	_MessageDescriptionCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Code.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MessageDescriptionCode */
typedef Code_t	 MessageDescriptionCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageDescriptionCode;
asn_struct_free_f MessageDescriptionCode_free;
asn_struct_print_f MessageDescriptionCode_print;
asn_constr_check_f MessageDescriptionCode_constraint;
ber_type_decoder_f MessageDescriptionCode_decode_ber;
der_type_encoder_f MessageDescriptionCode_encode_der;
xer_type_decoder_f MessageDescriptionCode_decode_xer;
xer_type_encoder_f MessageDescriptionCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageDescriptionCode_H_ */
#include <asn_internal.h>
