/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_MobileTerminatedCall_H_
#define	_MobileTerminatedCall_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MtBasicCallInformation;
struct LocationInformation;
struct ImeiOrEsn;
struct BasicServiceUsedList;
struct CamelServiceUsed;
struct OperatorSpecInfoList;

/* MobileTerminatedCall */
typedef struct MobileTerminatedCall {
	struct MtBasicCallInformation	*basicCallInformation	/* OPTIONAL */;
	struct LocationInformation	*locationInformation	/* OPTIONAL */;
	struct ImeiOrEsn	*equipmentIdentifier	/* OPTIONAL */;
	struct BasicServiceUsedList	*basicServiceUsedList	/* OPTIONAL */;
	struct CamelServiceUsed	*camelServiceUsed	/* OPTIONAL */;
	struct OperatorSpecInfoList	*operatorSpecInformation	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MobileTerminatedCall_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MobileTerminatedCall;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MtBasicCallInformation.h"
#include "LocationInformation.h"
#include "ImeiOrEsn.h"
#include "BasicServiceUsedList.h"
#include "CamelServiceUsed.h"
#include "OperatorSpecInfoList.h"

#endif	/* _MobileTerminatedCall_H_ */
#include <asn_internal.h>
