/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "MobileOriginatedCall.h"

static asn_TYPE_member_t asn_MBR_MobileOriginatedCall_1[] = {
	{ ATF_POINTER, 8, offsetof(struct MobileOriginatedCall, basicCallInformation),
		(ASN_TAG_CLASS_APPLICATION | (147 << 2)),
		0,
		&asn_DEF_MoBasicCallInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"basicCallInformation"
		},
	{ ATF_POINTER, 7, offsetof(struct MobileOriginatedCall, locationInformation),
		(ASN_TAG_CLASS_APPLICATION | (138 << 2)),
		0,
		&asn_DEF_LocationInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"locationInformation"
		},
	{ ATF_POINTER, 6, offsetof(struct MobileOriginatedCall, equipmentIdentifier),
		(ASN_TAG_CLASS_APPLICATION | (429 << 2)),
		0,
		&asn_DEF_ImeiOrEsn,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"equipmentIdentifier"
		},
	{ ATF_POINTER, 5, offsetof(struct MobileOriginatedCall, basicServiceUsedList),
		(ASN_TAG_CLASS_APPLICATION | (38 << 2)),
		0,
		&asn_DEF_BasicServiceUsedList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"basicServiceUsedList"
		},
	{ ATF_POINTER, 4, offsetof(struct MobileOriginatedCall, supplServiceCode),
		(ASN_TAG_CLASS_APPLICATION | (209 << 2)),
		0,
		&asn_DEF_SupplServiceCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"supplServiceCode"
		},
	{ ATF_POINTER, 3, offsetof(struct MobileOriginatedCall, thirdPartyInformation),
		(ASN_TAG_CLASS_APPLICATION | (219 << 2)),
		0,
		&asn_DEF_ThirdPartyInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"thirdPartyInformation"
		},
	{ ATF_POINTER, 2, offsetof(struct MobileOriginatedCall, camelServiceUsed),
		(ASN_TAG_CLASS_APPLICATION | (57 << 2)),
		0,
		&asn_DEF_CamelServiceUsed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"camelServiceUsed"
		},
	{ ATF_POINTER, 1, offsetof(struct MobileOriginatedCall, operatorSpecInformation),
		(ASN_TAG_CLASS_APPLICATION | (162 << 2)),
		0,
		&asn_DEF_OperatorSpecInfoList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operatorSpecInformation"
		},
};
static ber_tlv_tag_t asn_DEF_MobileOriginatedCall_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MobileOriginatedCall_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (38 << 2)), 3, 0, 0 }, /* basicServiceUsedList */
    { (ASN_TAG_CLASS_APPLICATION | (57 << 2)), 6, 0, 0 }, /* camelServiceUsed */
    { (ASN_TAG_CLASS_APPLICATION | (138 << 2)), 1, 0, 0 }, /* locationInformation */
    { (ASN_TAG_CLASS_APPLICATION | (147 << 2)), 0, 0, 0 }, /* basicCallInformation */
    { (ASN_TAG_CLASS_APPLICATION | (162 << 2)), 7, 0, 0 }, /* operatorSpecInformation */
    { (ASN_TAG_CLASS_APPLICATION | (209 << 2)), 4, 0, 0 }, /* supplServiceCode */
    { (ASN_TAG_CLASS_APPLICATION | (219 << 2)), 5, 0, 0 }, /* thirdPartyInformation */
    { (ASN_TAG_CLASS_APPLICATION | (429 << 2)), 2, 0, 0 } /* equipmentIdentifier */
};
static asn_SEQUENCE_specifics_t asn_SPC_MobileOriginatedCall_specs_1 = {
	sizeof(struct MobileOriginatedCall),
	offsetof(struct MobileOriginatedCall, _asn_ctx),
	asn_MAP_MobileOriginatedCall_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	7,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MobileOriginatedCall = {
	"MobileOriginatedCall",
	"MobileOriginatedCall",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MobileOriginatedCall_tags_1,
	sizeof(asn_DEF_MobileOriginatedCall_tags_1)
		/sizeof(asn_DEF_MobileOriginatedCall_tags_1[0]) - 1, /* 1 */
	asn_DEF_MobileOriginatedCall_tags_1,	/* Same as above */
	sizeof(asn_DEF_MobileOriginatedCall_tags_1)
		/sizeof(asn_DEF_MobileOriginatedCall_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_MobileOriginatedCall_1,
	8,	/* Elements count */
	&asn_SPC_MobileOriginatedCall_specs_1	/* Additional specs */
};

