/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_Msisdn_H_
#define	_Msisdn_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BCDString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Msisdn */
typedef BCDString_t	 Msisdn_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Msisdn;
asn_struct_free_f Msisdn_free;
asn_struct_print_f Msisdn_print;
asn_constr_check_f Msisdn_constraint;
ber_type_decoder_f Msisdn_decode_ber;
der_type_encoder_f Msisdn_encode_der;
xer_type_decoder_f Msisdn_decode_xer;
xer_type_encoder_f Msisdn_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Msisdn_H_ */
#include <asn_internal.h>
