/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_NetworkLocation_H_
#define	_NetworkLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RecEntityCode.h"
#include "CallReference.h"
#include "LocationArea.h"
#include "CellId.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NetworkLocation */
typedef struct NetworkLocation {
	RecEntityCode_t	*recEntityCode	/* OPTIONAL */;
	CallReference_t	*callReference	/* OPTIONAL */;
	LocationArea_t	*locationArea	/* OPTIONAL */;
	CellId_t	*cellId	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NetworkLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetworkLocation;

#ifdef __cplusplus
}
#endif

#endif	/* _NetworkLocation_H_ */
#include <asn_internal.h>
