/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "NetworkElement.h"

static asn_TYPE_member_t asn_MBR_NetworkElement_1[] = {
	{ ATF_POINTER, 2, offsetof(struct NetworkElement, elementType),
		(ASN_TAG_CLASS_APPLICATION | (438 << 2)),
		0,
		&asn_DEF_ElementType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"elementType"
		},
	{ ATF_POINTER, 1, offsetof(struct NetworkElement, elementId),
		(ASN_TAG_CLASS_APPLICATION | (437 << 2)),
		0,
		&asn_DEF_ElementId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"elementId"
		},
};
static ber_tlv_tag_t asn_DEF_NetworkElement_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (441 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_NetworkElement_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (437 << 2)), 1, 0, 0 }, /* elementId */
    { (ASN_TAG_CLASS_APPLICATION | (438 << 2)), 0, 0, 0 } /* elementType */
};
static asn_SEQUENCE_specifics_t asn_SPC_NetworkElement_specs_1 = {
	sizeof(struct NetworkElement),
	offsetof(struct NetworkElement, _asn_ctx),
	asn_MAP_NetworkElement_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_NetworkElement = {
	"NetworkElement",
	"NetworkElement",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_NetworkElement_tags_1,
	sizeof(asn_DEF_NetworkElement_tags_1)
		/sizeof(asn_DEF_NetworkElement_tags_1[0]) - 1, /* 1 */
	asn_DEF_NetworkElement_tags_1,	/* Same as above */
	sizeof(asn_DEF_NetworkElement_tags_1)
		/sizeof(asn_DEF_NetworkElement_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_NetworkElement_1,
	2,	/* Elements count */
	&asn_SPC_NetworkElement_specs_1	/* Additional specs */
};

