/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_NetworkAccessIdentifier_H_
#define	_NetworkAccessIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NetworkAccessIdentifier */
typedef AsciiString_t	 NetworkAccessIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetworkAccessIdentifier;
asn_struct_free_f NetworkAccessIdentifier_free;
asn_struct_print_f NetworkAccessIdentifier_print;
asn_constr_check_f NetworkAccessIdentifier_constraint;
ber_type_decoder_f NetworkAccessIdentifier_decode_ber;
der_type_encoder_f NetworkAccessIdentifier_encode_der;
xer_type_decoder_f NetworkAccessIdentifier_decode_xer;
xer_type_encoder_f NetworkAccessIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NetworkAccessIdentifier_H_ */
#include <asn_internal.h>
