/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_RecEntityCode_H_
#define	_RecEntityCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Code.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RecEntityCode */
typedef Code_t	 RecEntityCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RecEntityCode;
asn_struct_free_f RecEntityCode_free;
asn_struct_print_f RecEntityCode_print;
asn_constr_check_f RecEntityCode_constraint;
ber_type_decoder_f RecEntityCode_decode_ber;
der_type_encoder_f RecEntityCode_encode_der;
xer_type_decoder_f RecEntityCode_decode_xer;
xer_type_encoder_f RecEntityCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RecEntityCode_H_ */
#include <asn_internal.h>
