/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_Recipient_H_
#define	_Recipient_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PlmnId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Recipient */
typedef PlmnId_t	 Recipient_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Recipient;
asn_struct_free_f Recipient_free;
asn_struct_print_f Recipient_print;
asn_constr_check_f Recipient_constraint;
ber_type_decoder_f Recipient_decode_ber;
der_type_encoder_f Recipient_encode_der;
xer_type_decoder_f Recipient_decode_xer;
xer_type_encoder_f Recipient_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Recipient_H_ */
#include <asn_internal.h>
