/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_RequestedDeliveryTimeStamp_H_
#define	_RequestedDeliveryTimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DateTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RequestedDeliveryTimeStamp */
typedef DateTime_t	 RequestedDeliveryTimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestedDeliveryTimeStamp;
asn_struct_free_f RequestedDeliveryTimeStamp_free;
asn_struct_print_f RequestedDeliveryTimeStamp_print;
asn_constr_check_f RequestedDeliveryTimeStamp_constraint;
ber_type_decoder_f RequestedDeliveryTimeStamp_decode_ber;
der_type_encoder_f RequestedDeliveryTimeStamp_encode_der;
xer_type_decoder_f RequestedDeliveryTimeStamp_decode_xer;
xer_type_encoder_f RequestedDeliveryTimeStamp_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestedDeliveryTimeStamp_H_ */
#include <asn_internal.h>
