/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ResponseTime_H_
#define	_ResponseTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ResponseTime */
typedef long	 ResponseTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseTime;
asn_struct_free_f ResponseTime_free;
asn_struct_print_f ResponseTime_print;
asn_constr_check_f ResponseTime_constraint;
ber_type_decoder_f ResponseTime_decode_ber;
der_type_encoder_f ResponseTime_encode_der;
xer_type_decoder_f ResponseTime_decode_xer;
xer_type_encoder_f ResponseTime_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ResponseTime_H_ */
#include <asn_internal.h>
