/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ScuChargeType_H_
#define	_ScuChargeType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MessageStatus.h"
#include "PriorityCode.h"
#include "DistanceChargeBandCode.h"
#include "MessageType.h"
#include "MessageDescriptionCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ScuChargeType */
typedef struct ScuChargeType {
	MessageStatus_t	*messageStatus	/* OPTIONAL */;
	PriorityCode_t	*priorityCode	/* OPTIONAL */;
	DistanceChargeBandCode_t	*distanceChargeBandCode	/* OPTIONAL */;
	MessageType_t	*messageType	/* OPTIONAL */;
	MessageDescriptionCode_t	*messageDescriptionCode	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScuChargeType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScuChargeType;

#ifdef __cplusplus
}
#endif

#endif	/* _ScuChargeType_H_ */
#include <asn_internal.h>
