/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ScuTimeStamps_H_
#define	_ScuTimeStamps_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChargingPoint.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DateTime;

/* ScuTimeStamps */
typedef struct ScuTimeStamps {
	struct DateTime	*depositTimeStamp	/* OPTIONAL */;
	struct DateTime	*completionTimeStamp	/* OPTIONAL */;
	ChargingPoint_t	*chargingPoint	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScuTimeStamps_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScuTimeStamps;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DepositTimeStamp.h"
#include "CompletionTimeStamp.h"

#endif	/* _ScuTimeStamps_H_ */
#include <asn_internal.h>
