/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "ServingPartiesInformation.h"

static asn_TYPE_member_t asn_MBR_ServingPartiesInformation_1[] = {
	{ ATF_POINTER, 4, offsetof(struct ServingPartiesInformation, contentProviderName),
		(ASN_TAG_CLASS_APPLICATION | (334 << 2)),
		0,
		&asn_DEF_ContentProviderName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentProviderName"
		},
	{ ATF_POINTER, 3, offsetof(struct ServingPartiesInformation, contentProviderIdList),
		(ASN_TAG_CLASS_APPLICATION | (328 << 2)),
		0,
		&asn_DEF_ContentProviderIdList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentProviderIdList"
		},
	{ ATF_POINTER, 2, offsetof(struct ServingPartiesInformation, internetServiceProviderIdList),
		(ASN_TAG_CLASS_APPLICATION | (330 << 2)),
		0,
		&asn_DEF_InternetServiceProviderIdList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"internetServiceProviderIdList"
		},
	{ ATF_POINTER, 1, offsetof(struct ServingPartiesInformation, networkList),
		(ASN_TAG_CLASS_APPLICATION | (333 << 2)),
		0,
		&asn_DEF_NetworkList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkList"
		},
};
static ber_tlv_tag_t asn_DEF_ServingPartiesInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (335 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ServingPartiesInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (328 << 2)), 1, 0, 0 }, /* contentProviderIdList */
    { (ASN_TAG_CLASS_APPLICATION | (330 << 2)), 2, 0, 0 }, /* internetServiceProviderIdList */
    { (ASN_TAG_CLASS_APPLICATION | (333 << 2)), 3, 0, 0 }, /* networkList */
    { (ASN_TAG_CLASS_APPLICATION | (334 << 2)), 0, 0, 0 } /* contentProviderName */
};
static asn_SEQUENCE_specifics_t asn_SPC_ServingPartiesInformation_specs_1 = {
	sizeof(struct ServingPartiesInformation),
	offsetof(struct ServingPartiesInformation, _asn_ctx),
	asn_MAP_ServingPartiesInformation_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ServingPartiesInformation = {
	"ServingPartiesInformation",
	"ServingPartiesInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ServingPartiesInformation_tags_1,
	sizeof(asn_DEF_ServingPartiesInformation_tags_1)
		/sizeof(asn_DEF_ServingPartiesInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_ServingPartiesInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServingPartiesInformation_tags_1)
		/sizeof(asn_DEF_ServingPartiesInformation_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ServingPartiesInformation_1,
	4,	/* Elements count */
	&asn_SPC_ServingPartiesInformation_specs_1	/* Additional specs */
};

