/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_SimToolkitIndicator_H_
#define	_SimToolkitIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SimToolkitIndicator */
typedef AsciiString_t	 SimToolkitIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimToolkitIndicator;
asn_struct_free_f SimToolkitIndicator_free;
asn_struct_print_f SimToolkitIndicator_print;
asn_constr_check_f SimToolkitIndicator_constraint;
ber_type_decoder_f SimToolkitIndicator_decode_ber;
der_type_encoder_f SimToolkitIndicator_encode_der;
xer_type_decoder_f SimToolkitIndicator_decode_xer;
xer_type_encoder_f SimToolkitIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SimToolkitIndicator_H_ */
#include <asn_internal.h>
