/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "Taxation.h"

static asn_TYPE_member_t asn_MBR_Taxation_1[] = {
	{ ATF_POINTER, 5, offsetof(struct Taxation, taxCode),
		(ASN_TAG_CLASS_APPLICATION | (212 << 2)),
		0,
		&asn_DEF_TaxCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"taxCode"
		},
	{ ATF_POINTER, 4, offsetof(struct Taxation, taxType),
		(ASN_TAG_CLASS_APPLICATION | (217 << 2)),
		0,
		&asn_DEF_TaxType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"taxType"
		},
	{ ATF_POINTER, 3, offsetof(struct Taxation, taxRate),
		(ASN_TAG_CLASS_APPLICATION | (215 << 2)),
		0,
		&asn_DEF_TaxRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"taxRate"
		},
	{ ATF_POINTER, 2, offsetof(struct Taxation, chargeType),
		(ASN_TAG_CLASS_APPLICATION | (71 << 2)),
		0,
		&asn_DEF_ChargeType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargeType"
		},
	{ ATF_POINTER, 1, offsetof(struct Taxation, taxIndicator),
		(ASN_TAG_CLASS_APPLICATION | (432 << 2)),
		0,
		&asn_DEF_TaxIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"taxIndicator"
		},
};
static ber_tlv_tag_t asn_DEF_Taxation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (216 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Taxation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (71 << 2)), 3, 0, 0 }, /* chargeType */
    { (ASN_TAG_CLASS_APPLICATION | (212 << 2)), 0, 0, 0 }, /* taxCode */
    { (ASN_TAG_CLASS_APPLICATION | (215 << 2)), 2, 0, 0 }, /* taxRate */
    { (ASN_TAG_CLASS_APPLICATION | (217 << 2)), 1, 0, 0 }, /* taxType */
    { (ASN_TAG_CLASS_APPLICATION | (432 << 2)), 4, 0, 0 } /* taxIndicator */
};
static asn_SEQUENCE_specifics_t asn_SPC_Taxation_specs_1 = {
	sizeof(struct Taxation),
	offsetof(struct Taxation, _asn_ctx),
	asn_MAP_Taxation_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Taxation = {
	"Taxation",
	"Taxation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Taxation_tags_1,
	sizeof(asn_DEF_Taxation_tags_1)
		/sizeof(asn_DEF_Taxation_tags_1[0]) - 1, /* 1 */
	asn_DEF_Taxation_tags_1,	/* Same as above */
	sizeof(asn_DEF_Taxation_tags_1)
		/sizeof(asn_DEF_Taxation_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_Taxation_1,
	5,	/* Elements count */
	&asn_SPC_Taxation_specs_1	/* Additional specs */
};

