/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_ThirdPartyInformation_H_
#define	_ThirdPartyInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ThirdPartyNumber.h"
#include "ClirIndicator.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ThirdPartyInformation */
typedef struct ThirdPartyInformation {
	ThirdPartyNumber_t	*thirdPartyNumber	/* OPTIONAL */;
	ClirIndicator_t	*clirIndicator	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ThirdPartyInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ThirdPartyInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _ThirdPartyInformation_H_ */
#include <asn_internal.h>
