/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_TotalCharge_H_
#define	_TotalCharge_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AbsoluteAmount.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TotalCharge */
typedef AbsoluteAmount_t	 TotalCharge_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TotalCharge;
extern ber_tlv_tag_t asn_DEF_TotalCharge_tags_1[];
asn_struct_free_f TotalCharge_free;
asn_struct_print_f TotalCharge_print;
asn_constr_check_f TotalCharge_constraint;
ber_type_decoder_f TotalCharge_decode_ber;
der_type_encoder_f TotalCharge_encode_der;
xer_type_decoder_f TotalCharge_decode_xer;
xer_type_encoder_f TotalCharge_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TotalCharge_H_ */
#include <asn_internal.h>
