/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#include "TotalAdvisedChargeValue.h"

static asn_TYPE_member_t asn_MBR_TotalAdvisedChargeValue_1[] = {
	{ ATF_POINTER, 5, offsetof(struct TotalAdvisedChargeValue, advisedChargeCurrency),
		(ASN_TAG_CLASS_APPLICATION | (348 << 2)),
		0,
		&asn_DEF_AdvisedChargeCurrency,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"advisedChargeCurrency"
		},
	{ ATF_POINTER, 4, offsetof(struct TotalAdvisedChargeValue, totalAdvisedCharge),
		(ASN_TAG_CLASS_APPLICATION | (356 << 2)),
		0,
		&asn_DEF_TotalAdvisedCharge,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"totalAdvisedCharge"
		},
	{ ATF_POINTER, 3, offsetof(struct TotalAdvisedChargeValue, totalAdvisedChargeRefund),
		(ASN_TAG_CLASS_APPLICATION | (357 << 2)),
		0,
		&asn_DEF_TotalAdvisedChargeRefund,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"totalAdvisedChargeRefund"
		},
	{ ATF_POINTER, 2, offsetof(struct TotalAdvisedChargeValue, totalCommission),
		(ASN_TAG_CLASS_APPLICATION | (358 << 2)),
		0,
		&asn_DEF_TotalCommission,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"totalCommission"
		},
	{ ATF_POINTER, 1, offsetof(struct TotalAdvisedChargeValue, totalCommissionRefund),
		(ASN_TAG_CLASS_APPLICATION | (359 << 2)),
		0,
		&asn_DEF_TotalCommissionRefund,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"totalCommissionRefund"
		},
};
static ber_tlv_tag_t asn_DEF_TotalAdvisedChargeValue_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (360 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TotalAdvisedChargeValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (348 << 2)), 0, 0, 0 }, /* advisedChargeCurrency */
    { (ASN_TAG_CLASS_APPLICATION | (356 << 2)), 1, 0, 0 }, /* totalAdvisedCharge */
    { (ASN_TAG_CLASS_APPLICATION | (357 << 2)), 2, 0, 0 }, /* totalAdvisedChargeRefund */
    { (ASN_TAG_CLASS_APPLICATION | (358 << 2)), 3, 0, 0 }, /* totalCommission */
    { (ASN_TAG_CLASS_APPLICATION | (359 << 2)), 4, 0, 0 } /* totalCommissionRefund */
};
static asn_SEQUENCE_specifics_t asn_SPC_TotalAdvisedChargeValue_specs_1 = {
	sizeof(struct TotalAdvisedChargeValue),
	offsetof(struct TotalAdvisedChargeValue, _asn_ctx),
	asn_MAP_TotalAdvisedChargeValue_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TotalAdvisedChargeValue = {
	"TotalAdvisedChargeValue",
	"TotalAdvisedChargeValue",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TotalAdvisedChargeValue_tags_1,
	sizeof(asn_DEF_TotalAdvisedChargeValue_tags_1)
		/sizeof(asn_DEF_TotalAdvisedChargeValue_tags_1[0]) - 1, /* 1 */
	asn_DEF_TotalAdvisedChargeValue_tags_1,	/* Same as above */
	sizeof(asn_DEF_TotalAdvisedChargeValue_tags_1)
		/sizeof(asn_DEF_TotalAdvisedChargeValue_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_TotalAdvisedChargeValue_1,
	5,	/* Elements count */
	&asn_SPC_TotalAdvisedChargeValue_specs_1	/* Additional specs */
};

