/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_TotalCommission_H_
#define	_TotalCommission_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AbsoluteAmount.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TotalCommission */
typedef AbsoluteAmount_t	 TotalCommission_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TotalCommission;
asn_struct_free_f TotalCommission_free;
asn_struct_print_f TotalCommission_print;
asn_constr_check_f TotalCommission_constraint;
ber_type_decoder_f TotalCommission_decode_ber;
der_type_encoder_f TotalCommission_encode_der;
xer_type_decoder_f TotalCommission_decode_xer;
xer_type_encoder_f TotalCommission_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TotalCommission_H_ */
#include <asn_internal.h>
