/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_TotalDiscountRefund_H_
#define	_TotalDiscountRefund_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AbsoluteAmount.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TotalDiscountRefund */
typedef AbsoluteAmount_t	 TotalDiscountRefund_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TotalDiscountRefund;
asn_struct_free_f TotalDiscountRefund_free;
asn_struct_print_f TotalDiscountRefund_print;
asn_constr_check_f TotalDiscountRefund_constraint;
ber_type_decoder_f TotalDiscountRefund_decode_ber;
der_type_encoder_f TotalDiscountRefund_encode_der;
xer_type_decoder_f TotalDiscountRefund_decode_xer;
xer_type_encoder_f TotalDiscountRefund_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TotalDiscountRefund_H_ */
#include <asn_internal.h>
