/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_TotalDataVolume_H_
#define	_TotalDataVolume_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DataVolume.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TotalDataVolume */
typedef DataVolume_t	 TotalDataVolume_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TotalDataVolume;
asn_struct_free_f TotalDataVolume_free;
asn_struct_print_f TotalDataVolume_print;
asn_constr_check_f TotalDataVolume_constraint;
ber_type_decoder_f TotalDataVolume_decode_ber;
der_type_encoder_f TotalDataVolume_encode_der;
xer_type_decoder_f TotalDataVolume_decode_xer;
xer_type_encoder_f TotalDataVolume_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TotalDataVolume_H_ */
#include <asn_internal.h>
