/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_TrackingCustomerInformation_H_
#define	_TrackingCustomerInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TrackingCustomerIdList;
struct TrackingCustomerHomeIdList;
struct TrackingCustomerLocList;
struct TrackingCustomerEquipment;

/* TrackingCustomerInformation */
typedef struct TrackingCustomerInformation {
	struct TrackingCustomerIdList	*trackingCustomerIdList	/* OPTIONAL */;
	struct TrackingCustomerHomeIdList	*trackingCustomerHomeIdList	/* OPTIONAL */;
	struct TrackingCustomerLocList	*trackingCustomerLocList	/* OPTIONAL */;
	struct TrackingCustomerEquipment	*trackingCustomerEquipment	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrackingCustomerInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrackingCustomerInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TrackingCustomerIdList.h"
#include "TrackingCustomerHomeIdList.h"
#include "TrackingCustomerLocList.h"
#include "TrackingCustomerEquipment.h"

#endif	/* _TrackingCustomerInformation_H_ */
#include <asn_internal.h>
