/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_TransactionStatus_H_
#define	_TransactionStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TransactionStatus */
typedef long	 TransactionStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransactionStatus;
asn_struct_free_f TransactionStatus_free;
asn_struct_print_f TransactionStatus_print;
asn_constr_check_f TransactionStatus_constraint;
ber_type_decoder_f TransactionStatus_decode_ber;
der_type_encoder_f TransactionStatus_encode_der;
xer_type_decoder_f TransactionStatus_decode_xer;
xer_type_encoder_f TransactionStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TransactionStatus_H_ */
#include <asn_internal.h>
