/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP3.12.asn1"
 */

#ifndef	_UtcTimeOffsetCode_H_
#define	_UtcTimeOffsetCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Code.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UtcTimeOffsetCode */
typedef Code_t	 UtcTimeOffsetCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UtcTimeOffsetCode;
asn_struct_free_f UtcTimeOffsetCode_free;
asn_struct_print_f UtcTimeOffsetCode_print;
asn_constr_check_f UtcTimeOffsetCode_constraint;
ber_type_decoder_f UtcTimeOffsetCode_decode_ber;
der_type_encoder_f UtcTimeOffsetCode_encode_der;
xer_type_decoder_f UtcTimeOffsetCode_decode_xer;
xer_type_encoder_f UtcTimeOffsetCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UtcTimeOffsetCode_H_ */
#include <asn_internal.h>
