/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_AccountingInfo_H_
#define	_AccountingInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LocalCurrency.h"
#include "TapCurrency.h"
#include "TapDecimalPlaces.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TaxationList;
struct DiscountingList;
struct CurrencyConversionList;

/* AccountingInfo */
typedef struct AccountingInfo {
	struct TaxationList	*taxation	/* OPTIONAL */;
	struct DiscountingList	*discounting	/* OPTIONAL */;
	LocalCurrency_t	*localCurrency	/* OPTIONAL */;
	TapCurrency_t	*tapCurrency	/* OPTIONAL */;
	struct CurrencyConversionList	*currencyConversionInfo	/* OPTIONAL */;
	TapDecimalPlaces_t	*tapDecimalPlaces	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccountingInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccountingInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TaxationList.h"
#include "DiscountingList.h"
#include "CurrencyConversionList.h"

#endif	/* _AccountingInfo_H_ */
#include <asn_internal.h>
