/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "BasicService.h"

static asn_TYPE_member_t asn_MBR_BasicService_1[] = {
	{ ATF_POINTER, 6, offsetof(struct BasicService, serviceCode),
		(ASN_TAG_CLASS_APPLICATION | (426 << 2)),
		0,
		&asn_DEF_BasicServiceCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceCode"
		},
	{ ATF_POINTER, 5, offsetof(struct BasicService, transparencyIndicator),
		(ASN_TAG_CLASS_APPLICATION | (228 << 2)),
		0,
		&asn_DEF_TransparencyIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transparencyIndicator"
		},
	{ ATF_POINTER, 4, offsetof(struct BasicService, fnur),
		(ASN_TAG_CLASS_APPLICATION | (111 << 2)),
		0,
		&asn_DEF_Fnur,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fnur"
		},
	{ ATF_POINTER, 3, offsetof(struct BasicService, userProtocolIndicator),
		(ASN_TAG_CLASS_APPLICATION | (280 << 2)),
		0,
		&asn_DEF_UserProtocolIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userProtocolIndicator"
		},
	{ ATF_POINTER, 2, offsetof(struct BasicService, guaranteedBitRate),
		(ASN_TAG_CLASS_APPLICATION | (420 << 2)),
		0,
		&asn_DEF_GuaranteedBitRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"guaranteedBitRate"
		},
	{ ATF_POINTER, 1, offsetof(struct BasicService, maximumBitRate),
		(ASN_TAG_CLASS_APPLICATION | (421 << 2)),
		0,
		&asn_DEF_MaximumBitRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"maximumBitRate"
		},
};
static ber_tlv_tag_t asn_DEF_BasicService_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (36 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BasicService_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (111 << 2)), 2, 0, 0 }, /* fnur */
    { (ASN_TAG_CLASS_APPLICATION | (228 << 2)), 1, 0, 0 }, /* transparencyIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (280 << 2)), 3, 0, 0 }, /* userProtocolIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (420 << 2)), 4, 0, 0 }, /* guaranteedBitRate */
    { (ASN_TAG_CLASS_APPLICATION | (421 << 2)), 5, 0, 0 }, /* maximumBitRate */
    { (ASN_TAG_CLASS_APPLICATION | (426 << 2)), 0, 0, 0 } /* serviceCode */
};
static asn_SEQUENCE_specifics_t asn_SPC_BasicService_specs_1 = {
	sizeof(struct BasicService),
	offsetof(struct BasicService, _asn_ctx),
	asn_MAP_BasicService_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BasicService = {
	"BasicService",
	"BasicService",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BasicService_tags_1,
	sizeof(asn_DEF_BasicService_tags_1)
		/sizeof(asn_DEF_BasicService_tags_1[0]) - 1, /* 1 */
	asn_DEF_BasicService_tags_1,	/* Same as above */
	sizeof(asn_DEF_BasicService_tags_1)
		/sizeof(asn_DEF_BasicService_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_BasicService_1,
	6,	/* Elements count */
	&asn_SPC_BasicService_specs_1	/* Additional specs */
};

