/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_CallEventDetail_H_
#define	_CallEventDetail_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MobileOriginatedCall.h"
#include "MobileTerminatedCall.h"
#include "SupplServiceEvent.h"
#include "ServiceCentreUsage.h"
#include "GprsCall.h"
#include "ContentTransaction.h"
#include "LocationService.h"
#include "MessagingEvent.h"
#include "MobileSession.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallEventDetail_PR {
	CallEventDetail_PR_NOTHING,	/* No components present */
	CallEventDetail_PR_mobileOriginatedCall,
	CallEventDetail_PR_mobileTerminatedCall,
	CallEventDetail_PR_supplServiceEvent,
	CallEventDetail_PR_serviceCentreUsage,
	CallEventDetail_PR_gprsCall,
	CallEventDetail_PR_contentTransaction,
	CallEventDetail_PR_locationService,
	CallEventDetail_PR_messagingEvent,
	CallEventDetail_PR_mobileSession,
	/* Extensions may appear below */
	
} CallEventDetail_PR;

/* CallEventDetail */
typedef struct CallEventDetail {
	CallEventDetail_PR present;
	union CallEventDetail_u {
		MobileOriginatedCall_t	 mobileOriginatedCall;
		MobileTerminatedCall_t	 mobileTerminatedCall;
		SupplServiceEvent_t	 supplServiceEvent;
		ServiceCentreUsage_t	 serviceCentreUsage;
		GprsCall_t	 gprsCall;
		ContentTransaction_t	 contentTransaction;
		LocationService_t	 locationService;
		MessagingEvent_t	 messagingEvent;
		MobileSession_t	 mobileSession;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallEventDetail_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallEventDetail;

#ifdef __cplusplus
}
#endif

#endif	/* _CallEventDetail_H_ */
#include <asn_internal.h>
