/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_ChargedPartyInformation_H_
#define	_ChargedPartyInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargedPartyIdList;
struct ChargedPartyHomeIdList;
struct ChargedPartyLocationList;
struct ChargedPartyEquipment;

/* ChargedPartyInformation */
typedef struct ChargedPartyInformation {
	struct ChargedPartyIdList	*chargedPartyIdList	/* OPTIONAL */;
	struct ChargedPartyHomeIdList	*chargedPartyHomeIdList	/* OPTIONAL */;
	struct ChargedPartyLocationList	*chargedPartyLocationList	/* OPTIONAL */;
	struct ChargedPartyEquipment	*chargedPartyEquipment	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChargedPartyInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargedPartyInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargedPartyIdList.h"
#include "ChargedPartyHomeIdList.h"
#include "ChargedPartyLocationList.h"
#include "ChargedPartyEquipment.h"

#endif	/* _ChargedPartyInformation_H_ */
#include <asn_internal.h>
