/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_Commission_H_
#define	_Commission_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Charge.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Commission */
typedef Charge_t	 Commission_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Commission;
asn_struct_free_f Commission_free;
asn_struct_print_f Commission_print;
asn_constr_check_f Commission_constraint;
ber_type_decoder_f Commission_decode_ber;
der_type_encoder_f Commission_encode_der;
xer_type_decoder_f Commission_decode_xer;
xer_type_encoder_f Commission_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Commission_H_ */
#include <asn_internal.h>
