/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_ContentChargingPoint_H_
#define	_ContentChargingPoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ContentChargingPoint */
typedef long	 ContentChargingPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContentChargingPoint;
asn_struct_free_f ContentChargingPoint_free;
asn_struct_print_f ContentChargingPoint_print;
asn_constr_check_f ContentChargingPoint_constraint;
ber_type_decoder_f ContentChargingPoint_decode_ber;
der_type_encoder_f ContentChargingPoint_encode_der;
xer_type_decoder_f ContentChargingPoint_decode_xer;
xer_type_encoder_f ContentChargingPoint_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ContentChargingPoint_H_ */
#include <asn_internal.h>
