/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "ContentServiceUsed.h"

static asn_TYPE_member_t asn_MBR_ContentServiceUsed_1[] = {
	{ ATF_POINTER, 15, offsetof(struct ContentServiceUsed, contentTransactionCode),
		(ASN_TAG_CLASS_APPLICATION | (336 << 2)),
		0,
		&asn_DEF_ContentTransactionCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentTransactionCode"
		},
	{ ATF_POINTER, 14, offsetof(struct ContentServiceUsed, contentTransactionType),
		(ASN_TAG_CLASS_APPLICATION | (337 << 2)),
		0,
		&asn_DEF_ContentTransactionType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentTransactionType"
		},
	{ ATF_POINTER, 13, offsetof(struct ContentServiceUsed, objectType),
		(ASN_TAG_CLASS_APPLICATION | (281 << 2)),
		0,
		&asn_DEF_ObjectType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"objectType"
		},
	{ ATF_POINTER, 12, offsetof(struct ContentServiceUsed, transactionDescriptionSupp),
		(ASN_TAG_CLASS_APPLICATION | (338 << 2)),
		0,
		&asn_DEF_TransactionDescriptionSupp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transactionDescriptionSupp"
		},
	{ ATF_POINTER, 11, offsetof(struct ContentServiceUsed, transactionShortDescription),
		(ASN_TAG_CLASS_APPLICATION | (340 << 2)),
		0,
		&asn_DEF_TransactionShortDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transactionShortDescription"
		},
	{ ATF_POINTER, 10, offsetof(struct ContentServiceUsed, transactionDetailDescription),
		(ASN_TAG_CLASS_APPLICATION | (339 << 2)),
		0,
		&asn_DEF_TransactionDetailDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transactionDetailDescription"
		},
	{ ATF_POINTER, 9, offsetof(struct ContentServiceUsed, transactionIdentifier),
		(ASN_TAG_CLASS_APPLICATION | (341 << 2)),
		0,
		&asn_DEF_TransactionIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transactionIdentifier"
		},
	{ ATF_POINTER, 8, offsetof(struct ContentServiceUsed, transactionAuthCode),
		(ASN_TAG_CLASS_APPLICATION | (342 << 2)),
		0,
		&asn_DEF_TransactionAuthCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transactionAuthCode"
		},
	{ ATF_POINTER, 7, offsetof(struct ContentServiceUsed, dataVolumeIncoming),
		(ASN_TAG_CLASS_APPLICATION | (250 << 2)),
		0,
		&asn_DEF_DataVolumeIncoming,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeIncoming"
		},
	{ ATF_POINTER, 6, offsetof(struct ContentServiceUsed, dataVolumeOutgoing),
		(ASN_TAG_CLASS_APPLICATION | (251 << 2)),
		0,
		&asn_DEF_DataVolumeOutgoing,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeOutgoing"
		},
	{ ATF_POINTER, 5, offsetof(struct ContentServiceUsed, totalDataVolume),
		(ASN_TAG_CLASS_APPLICATION | (343 << 2)),
		0,
		&asn_DEF_TotalDataVolume,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"totalDataVolume"
		},
	{ ATF_POINTER, 4, offsetof(struct ContentServiceUsed, chargeRefundIndicator),
		(ASN_TAG_CLASS_APPLICATION | (344 << 2)),
		0,
		&asn_DEF_ChargeRefundIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargeRefundIndicator"
		},
	{ ATF_POINTER, 3, offsetof(struct ContentServiceUsed, contentChargingPoint),
		(ASN_TAG_CLASS_APPLICATION | (345 << 2)),
		0,
		&asn_DEF_ContentChargingPoint,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentChargingPoint"
		},
	{ ATF_POINTER, 2, offsetof(struct ContentServiceUsed, chargeInformationList),
		(ASN_TAG_CLASS_APPLICATION | (70 << 2)),
		0,
		&asn_DEF_ChargeInformationList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargeInformationList"
		},
	{ ATF_POINTER, 1, offsetof(struct ContentServiceUsed, advisedChargeInformation),
		(ASN_TAG_CLASS_APPLICATION | (351 << 2)),
		0,
		&asn_DEF_AdvisedChargeInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"advisedChargeInformation"
		},
};
static ber_tlv_tag_t asn_DEF_ContentServiceUsed_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (352 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ContentServiceUsed_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (70 << 2)), 13, 0, 0 }, /* chargeInformationList */
    { (ASN_TAG_CLASS_APPLICATION | (250 << 2)), 8, 0, 0 }, /* dataVolumeIncoming */
    { (ASN_TAG_CLASS_APPLICATION | (251 << 2)), 9, 0, 0 }, /* dataVolumeOutgoing */
    { (ASN_TAG_CLASS_APPLICATION | (281 << 2)), 2, 0, 0 }, /* objectType */
    { (ASN_TAG_CLASS_APPLICATION | (336 << 2)), 0, 0, 0 }, /* contentTransactionCode */
    { (ASN_TAG_CLASS_APPLICATION | (337 << 2)), 1, 0, 0 }, /* contentTransactionType */
    { (ASN_TAG_CLASS_APPLICATION | (338 << 2)), 3, 0, 0 }, /* transactionDescriptionSupp */
    { (ASN_TAG_CLASS_APPLICATION | (339 << 2)), 5, 0, 0 }, /* transactionDetailDescription */
    { (ASN_TAG_CLASS_APPLICATION | (340 << 2)), 4, 0, 0 }, /* transactionShortDescription */
    { (ASN_TAG_CLASS_APPLICATION | (341 << 2)), 6, 0, 0 }, /* transactionIdentifier */
    { (ASN_TAG_CLASS_APPLICATION | (342 << 2)), 7, 0, 0 }, /* transactionAuthCode */
    { (ASN_TAG_CLASS_APPLICATION | (343 << 2)), 10, 0, 0 }, /* totalDataVolume */
    { (ASN_TAG_CLASS_APPLICATION | (344 << 2)), 11, 0, 0 }, /* chargeRefundIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (345 << 2)), 12, 0, 0 }, /* contentChargingPoint */
    { (ASN_TAG_CLASS_APPLICATION | (351 << 2)), 14, 0, 0 } /* advisedChargeInformation */
};
static asn_SEQUENCE_specifics_t asn_SPC_ContentServiceUsed_specs_1 = {
	sizeof(struct ContentServiceUsed),
	offsetof(struct ContentServiceUsed, _asn_ctx),
	asn_MAP_ContentServiceUsed_tag2el_1,
	15,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	14,	/* Start extensions */
	16	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ContentServiceUsed = {
	"ContentServiceUsed",
	"ContentServiceUsed",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ContentServiceUsed_tags_1,
	sizeof(asn_DEF_ContentServiceUsed_tags_1)
		/sizeof(asn_DEF_ContentServiceUsed_tags_1[0]) - 1, /* 1 */
	asn_DEF_ContentServiceUsed_tags_1,	/* Same as above */
	sizeof(asn_DEF_ContentServiceUsed_tags_1)
		/sizeof(asn_DEF_ContentServiceUsed_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ContentServiceUsed_1,
	15,	/* Elements count */
	&asn_SPC_ContentServiceUsed_specs_1	/* Additional specs */
};

