/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_ContentProvider_H_
#define	_ContentProvider_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ContentProviderIdType.h"
#include "ContentProviderIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ContentProvider */
typedef struct ContentProvider {
	ContentProviderIdType_t	*contentProviderIdType	/* OPTIONAL */;
	ContentProviderIdentifier_t	*contentProviderIdentifier	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ContentProvider_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContentProvider;

#ifdef __cplusplus
}
#endif

#endif	/* _ContentProvider_H_ */
#include <asn_internal.h>
