/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_DateTime_H_
#define	_DateTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LocalTimeStamp.h"
#include "UtcTimeOffsetCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DateTime */
typedef struct DateTime {
	LocalTimeStamp_t	*localTimeStamp	/* OPTIONAL */;
	UtcTimeOffsetCode_t	*utcTimeOffsetCode	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DateTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DateTime;

#ifdef __cplusplus
}
#endif

#endif	/* _DateTime_H_ */
#include <asn_internal.h>
