/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_DestinationNetwork_H_
#define	_DestinationNetwork_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NetworkId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DestinationNetwork */
typedef NetworkId_t	 DestinationNetwork_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DestinationNetwork;
asn_struct_free_f DestinationNetwork_free;
asn_struct_print_f DestinationNetwork_print;
asn_constr_check_f DestinationNetwork_constraint;
ber_type_decoder_f DestinationNetwork_decode_ber;
der_type_encoder_f DestinationNetwork_encode_der;
xer_type_decoder_f DestinationNetwork_decode_xer;
xer_type_encoder_f DestinationNetwork_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DestinationNetwork_H_ */
#include <asn_internal.h>
