/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_DiscountingList_H_
#define	_DiscountingList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Discounting;

/* DiscountingList */
typedef struct DiscountingList {
	A_SEQUENCE_OF(struct Discounting) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiscountingList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiscountingList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Discounting.h"

#endif	/* _DiscountingList_H_ */
#include <asn_internal.h>
