/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_Discount_H_
#define	_Discount_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DiscountValue.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Discount */
typedef DiscountValue_t	 Discount_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Discount;
asn_struct_free_f Discount_free;
asn_struct_print_f Discount_print;
asn_constr_check_f Discount_constraint;
ber_type_decoder_f Discount_decode_ber;
der_type_encoder_f Discount_encode_der;
xer_type_decoder_f Discount_decode_xer;
xer_type_encoder_f Discount_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Discount_H_ */
#include <asn_internal.h>
