/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_DiscountValue_H_
#define	_DiscountValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AbsoluteAmount.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DiscountValue */
typedef AbsoluteAmount_t	 DiscountValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiscountValue;
asn_struct_free_f DiscountValue_free;
asn_struct_print_f DiscountValue_print;
asn_constr_check_f DiscountValue_constraint;
ber_type_decoder_f DiscountValue_decode_ber;
der_type_encoder_f DiscountValue_encode_der;
xer_type_decoder_f DiscountValue_decode_xer;
xer_type_encoder_f DiscountValue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DiscountValue_H_ */
#include <asn_internal.h>
