/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_DiscountApplied_H_
#define	_DiscountApplied_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FixedDiscountValue.h"
#include "DiscountRate.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DiscountApplied_PR {
	DiscountApplied_PR_NOTHING,	/* No components present */
	DiscountApplied_PR_fixedDiscountValue,
	DiscountApplied_PR_discountRate,
	/* Extensions may appear below */
	
} DiscountApplied_PR;

/* DiscountApplied */
typedef struct DiscountApplied {
	DiscountApplied_PR present;
	union DiscountApplied_u {
		FixedDiscountValue_t	 fixedDiscountValue;
		DiscountRate_t	 discountRate;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiscountApplied_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiscountApplied;

#ifdef __cplusplus
}
#endif

#endif	/* _DiscountApplied_H_ */
#include <asn_internal.h>
