/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_DistanceChargeBandCode_H_
#define	_DistanceChargeBandCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DistanceChargeBandCode */
typedef AsciiString_t	 DistanceChargeBandCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DistanceChargeBandCode;
asn_struct_free_f DistanceChargeBandCode_free;
asn_struct_print_f DistanceChargeBandCode_print;
asn_constr_check_f DistanceChargeBandCode_constraint;
ber_type_decoder_f DistanceChargeBandCode_decode_ber;
der_type_encoder_f DistanceChargeBandCode_encode_der;
xer_type_decoder_f DistanceChargeBandCode_decode_xer;
xer_type_encoder_f DistanceChargeBandCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DistanceChargeBandCode_H_ */
#include <asn_internal.h>
