/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_ErrorContextList_H_
#define	_ErrorContextList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ErrorContext;

/* ErrorContextList */
typedef struct ErrorContextList {
	A_SEQUENCE_OF(struct ErrorContext) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ErrorContextList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ErrorContextList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ErrorContext.h"

#endif	/* _ErrorContextList_H_ */
#include <asn_internal.h>
