/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_EventReference_H_
#define	_EventReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EventReference */
typedef AsciiString_t	 EventReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventReference;
asn_struct_free_f EventReference_free;
asn_struct_print_f EventReference_print;
asn_constr_check_f EventReference_constraint;
ber_type_decoder_f EventReference_decode_ber;
der_type_encoder_f EventReference_encode_der;
xer_type_decoder_f EventReference_decode_xer;
xer_type_encoder_f EventReference_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EventReference_H_ */
#include <asn_internal.h>
