/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#include "FatalReturn.h"

static asn_TYPE_member_t asn_MBR_FatalReturn_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FatalReturn, fileSequenceNumber),
		(ASN_TAG_CLASS_APPLICATION | (109 << 2)),
		0,
		&asn_DEF_FileSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fileSequenceNumber"
		},
	{ ATF_POINTER, 8, offsetof(struct FatalReturn, transferBatchError),
		(ASN_TAG_CLASS_APPLICATION | (542 << 2)),
		0,
		&asn_DEF_TransferBatchError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transferBatchError"
		},
	{ ATF_POINTER, 7, offsetof(struct FatalReturn, notificationError),
		(ASN_TAG_CLASS_APPLICATION | (552 << 2)),
		0,
		&asn_DEF_NotificationError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"notificationError"
		},
	{ ATF_POINTER, 6, offsetof(struct FatalReturn, batchControlError),
		(ASN_TAG_CLASS_APPLICATION | (517 << 2)),
		0,
		&asn_DEF_BatchControlError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"batchControlError"
		},
	{ ATF_POINTER, 5, offsetof(struct FatalReturn, accountingInfoError),
		(ASN_TAG_CLASS_APPLICATION | (512 << 2)),
		0,
		&asn_DEF_AccountingInfoError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accountingInfoError"
		},
	{ ATF_POINTER, 4, offsetof(struct FatalReturn, networkInfoError),
		(ASN_TAG_CLASS_APPLICATION | (523 << 2)),
		0,
		&asn_DEF_NetworkInfoError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkInfoError"
		},
	{ ATF_POINTER, 3, offsetof(struct FatalReturn, messageDescriptionError),
		(ASN_TAG_CLASS_APPLICATION | (522 << 2)),
		0,
		&asn_DEF_MessageDescriptionError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"messageDescriptionError"
		},
	{ ATF_POINTER, 2, offsetof(struct FatalReturn, auditControlInfoError),
		(ASN_TAG_CLASS_APPLICATION | (513 << 2)),
		0,
		&asn_DEF_AuditControlInfoError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"auditControlInfoError"
		},
	{ ATF_POINTER, 1, offsetof(struct FatalReturn, operatorSpecList),
		(ASN_TAG_CLASS_APPLICATION | (551 << 2)),
		0,
		&asn_DEF_OperatorSpecList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operatorSpecList"
		},
};
static ber_tlv_tag_t asn_DEF_FatalReturn_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (539 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_FatalReturn_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (109 << 2)), 0, 0, 0 }, /* fileSequenceNumber */
    { (ASN_TAG_CLASS_APPLICATION | (512 << 2)), 4, 0, 0 }, /* accountingInfoError */
    { (ASN_TAG_CLASS_APPLICATION | (513 << 2)), 7, 0, 0 }, /* auditControlInfoError */
    { (ASN_TAG_CLASS_APPLICATION | (517 << 2)), 3, 0, 0 }, /* batchControlError */
    { (ASN_TAG_CLASS_APPLICATION | (522 << 2)), 6, 0, 0 }, /* messageDescriptionError */
    { (ASN_TAG_CLASS_APPLICATION | (523 << 2)), 5, 0, 0 }, /* networkInfoError */
    { (ASN_TAG_CLASS_APPLICATION | (542 << 2)), 1, 0, 0 }, /* transferBatchError */
    { (ASN_TAG_CLASS_APPLICATION | (551 << 2)), 8, 0, 0 }, /* operatorSpecList */
    { (ASN_TAG_CLASS_APPLICATION | (552 << 2)), 2, 0, 0 } /* notificationError */
};
static asn_SEQUENCE_specifics_t asn_SPC_FatalReturn_specs_1 = {
	sizeof(struct FatalReturn),
	offsetof(struct FatalReturn, _asn_ctx),
	asn_MAP_FatalReturn_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	8,	/* Start extensions */
	10	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_FatalReturn = {
	"FatalReturn",
	"FatalReturn",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_FatalReturn_tags_1,
	sizeof(asn_DEF_FatalReturn_tags_1)
		/sizeof(asn_DEF_FatalReturn_tags_1[0]) - 1, /* 1 */
	asn_DEF_FatalReturn_tags_1,	/* Same as above */
	sizeof(asn_DEF_FatalReturn_tags_1)
		/sizeof(asn_DEF_FatalReturn_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_FatalReturn_1,
	9,	/* Elements count */
	&asn_SPC_FatalReturn_specs_1	/* Additional specs */
};

