/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_FileTypeIndicator_H_
#define	_FileTypeIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FileTypeIndicator */
typedef AsciiString_t	 FileTypeIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileTypeIndicator;
asn_struct_free_f FileTypeIndicator_free;
asn_struct_print_f FileTypeIndicator_print;
asn_constr_check_f FileTypeIndicator_constraint;
ber_type_decoder_f FileTypeIndicator_decode_ber;
der_type_encoder_f FileTypeIndicator_encode_der;
xer_type_decoder_f FileTypeIndicator_decode_xer;
xer_type_encoder_f FileTypeIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FileTypeIndicator_H_ */
#include <asn_internal.h>
