/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_HomeLocationInformation_H_
#define	_HomeLocationInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HomeBid.h"
#include "HomeLocationDescription.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HomeLocationInformation */
typedef struct HomeLocationInformation {
	HomeBid_t	*homeBid	/* OPTIONAL */;
	HomeLocationDescription_t	*homeLocationDescription	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HomeLocationInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HomeLocationInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _HomeLocationInformation_H_ */
#include <asn_internal.h>
