/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_ItemOffset_H_
#define	_ItemOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ItemOffset */
typedef long	 ItemOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ItemOffset;
asn_struct_free_f ItemOffset_free;
asn_struct_print_f ItemOffset_print;
asn_constr_check_f ItemOffset_constraint;
ber_type_decoder_f ItemOffset_decode_ber;
der_type_encoder_f ItemOffset_encode_der;
xer_type_decoder_f ItemOffset_decode_xer;
xer_type_encoder_f ItemOffset_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ItemOffset_H_ */
#include <asn_internal.h>
