/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_LocationIdType_H_
#define	_LocationIdType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LocationIdType */
typedef long	 LocationIdType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocationIdType;
asn_struct_free_f LocationIdType_free;
asn_struct_print_f LocationIdType_print;
asn_constr_check_f LocationIdType_constraint;
ber_type_decoder_f LocationIdType_decode_ber;
der_type_encoder_f LocationIdType_encode_der;
xer_type_decoder_f LocationIdType_decode_xer;
xer_type_encoder_f LocationIdType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LocationIdType_H_ */
#include <asn_internal.h>
