/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_MoBasicCallInformation_H_
#define	_MoBasicCallInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RapFileSequenceNumber.h"
#include "DestinationNetwork.h"
#include "TotalCallEventDuration.h"
#include "SimToolkitIndicator.h"
#include "CauseForTerm.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargeableSubscriber;
struct Destination;
struct DateTime;

/* MoBasicCallInformation */
typedef struct MoBasicCallInformation {
	struct ChargeableSubscriber	*chargeableSubscriber	/* OPTIONAL */;
	RapFileSequenceNumber_t	*rapFileSequenceNumber	/* OPTIONAL */;
	struct Destination	*destination	/* OPTIONAL */;
	DestinationNetwork_t	*destinationNetwork	/* OPTIONAL */;
	struct DateTime	*callEventStartTimeStamp	/* OPTIONAL */;
	TotalCallEventDuration_t	*totalCallEventDuration	/* OPTIONAL */;
	SimToolkitIndicator_t	*simToolkitIndicator	/* OPTIONAL */;
	CauseForTerm_t	*causeForTerm	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MoBasicCallInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MoBasicCallInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargeableSubscriber.h"
#include "Destination.h"
#include "CallEventStartTimeStamp.h"

#endif	/* _MoBasicCallInformation_H_ */
#include <asn_internal.h>
