/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_NonChargedPartyNumber_H_
#define	_NonChargedPartyNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AddressStringDigits.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NonChargedPartyNumber */
typedef AddressStringDigits_t	 NonChargedPartyNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NonChargedPartyNumber;
asn_struct_free_f NonChargedPartyNumber_free;
asn_struct_print_f NonChargedPartyNumber_print;
asn_constr_check_f NonChargedPartyNumber_constraint;
ber_type_decoder_f NonChargedPartyNumber_decode_ber;
der_type_encoder_f NonChargedPartyNumber_encode_der;
xer_type_decoder_f NonChargedPartyNumber_decode_xer;
xer_type_encoder_f NonChargedPartyNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NonChargedPartyNumber_H_ */
#include <asn_internal.h>
