/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_PositioningMethod_H_
#define	_PositioningMethod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PositioningMethod */
typedef long	 PositioningMethod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositioningMethod;
asn_struct_free_f PositioningMethod_free;
asn_struct_print_f PositioningMethod_print;
asn_constr_check_f PositioningMethod_constraint;
ber_type_decoder_f PositioningMethod_decode_ber;
der_type_encoder_f PositioningMethod_encode_der;
xer_type_decoder_f PositioningMethod_decode_xer;
xer_type_encoder_f PositioningMethod_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PositioningMethod_H_ */
#include <asn_internal.h>
