/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_RapAuditControlInfo_H_
#define	_RapAuditControlInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TotalSevereReturnValue.h"
#include "ReturnDetailsCount.h"
#include "TotalSevereReturnTax.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OperatorSpecList;

/* RapAuditControlInfo */
typedef struct RapAuditControlInfo {
	TotalSevereReturnValue_t	 totalSevereReturnValue;
	ReturnDetailsCount_t	 returnDetailsCount;
	struct OperatorSpecList	*operatorSpecList	/* OPTIONAL */;
	TotalSevereReturnTax_t	*totalSevereReturnTax	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RapAuditControlInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RapAuditControlInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OperatorSpecList.h"

#endif	/* _RapAuditControlInfo_H_ */
#include <asn_internal.h>
