/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_RapBatchControlInfo_H_
#define	_RapBatchControlInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Sender.h"
#include "Recipient.h"
#include "RapFileSequenceNumber.h"
#include "RapFileCreationTimeStamp.h"
#include "RapFileAvailableTimeStamp.h"
#include "SpecificationVersionNumber.h"
#include "ReleaseVersionNumber.h"
#include "RapSpecificationVersionNumber.h"
#include "RapReleaseVersionNumber.h"
#include "FileTypeIndicator.h"
#include "RoamingPartner.h"
#include "TapDecimalPlaces.h"
#include "TapCurrency.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OperatorSpecList;

/* RapBatchControlInfo */
typedef struct RapBatchControlInfo {
	Sender_t	 sender;
	Recipient_t	 recipient;
	RapFileSequenceNumber_t	 rapFileSequenceNumber;
	RapFileCreationTimeStamp_t	 rapFileCreationTimeStamp;
	RapFileAvailableTimeStamp_t	 rapFileAvailableTimeStamp;
	SpecificationVersionNumber_t	*specificationVersionNumber	/* OPTIONAL */;
	ReleaseVersionNumber_t	*releaseVersionNumber	/* OPTIONAL */;
	RapSpecificationVersionNumber_t	 rapSpecificationVersionNumber;
	RapReleaseVersionNumber_t	 rapReleaseVersionNumber;
	FileTypeIndicator_t	*fileTypeIndicator	/* OPTIONAL */;
	RoamingPartner_t	*roamingPartner	/* OPTIONAL */;
	struct OperatorSpecList	*operatorSpecList	/* OPTIONAL */;
	TapDecimalPlaces_t	*tapDecimalPlaces	/* OPTIONAL */;
	TapCurrency_t	*tapCurrency	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RapBatchControlInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RapBatchControlInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OperatorSpecList.h"

#endif	/* _RapBatchControlInfo_H_ */
#include <asn_internal.h>
