/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_RapDataInterChange_H_
#define	_RapDataInterChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ReturnBatch.h"
#include "Acknowledgement.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RapDataInterChange_PR {
	RapDataInterChange_PR_NOTHING,	/* No components present */
	RapDataInterChange_PR_returnBatch,
	RapDataInterChange_PR_acknowledgement,
	/* Extensions may appear below */
	
} RapDataInterChange_PR;

/* RapDataInterChange */
typedef struct RapDataInterChange {
	RapDataInterChange_PR present;
	union RapDataInterChange_u {
		ReturnBatch_t	 returnBatch;
		Acknowledgement_t	 acknowledgement;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RapDataInterChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RapDataInterChange;

#ifdef __cplusplus
}
#endif

#endif	/* _RapDataInterChange_H_ */
#include <asn_internal.h>
