/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_RapFileCreationTimeStamp_H_
#define	_RapFileCreationTimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DateTimeLong.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RapFileCreationTimeStamp */
typedef DateTimeLong_t	 RapFileCreationTimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RapFileCreationTimeStamp;
asn_struct_free_f RapFileCreationTimeStamp_free;
asn_struct_print_f RapFileCreationTimeStamp_print;
asn_constr_check_f RapFileCreationTimeStamp_constraint;
ber_type_decoder_f RapFileCreationTimeStamp_decode_ber;
der_type_encoder_f RapFileCreationTimeStamp_encode_der;
xer_type_decoder_f RapFileCreationTimeStamp_decode_xer;
xer_type_encoder_f RapFileCreationTimeStamp_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RapFileCreationTimeStamp_H_ */
#include <asn_internal.h>
