/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "RAP-0105"
 * 	found in "RAP_ASN_specification.txt"
 */

#ifndef	_RapReleaseVersionNumber_H_
#define	_RapReleaseVersionNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RapReleaseVersionNumber */
typedef long	 RapReleaseVersionNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RapReleaseVersionNumber;
asn_struct_free_f RapReleaseVersionNumber_free;
asn_struct_print_f RapReleaseVersionNumber_print;
asn_constr_check_f RapReleaseVersionNumber_constraint;
ber_type_decoder_f RapReleaseVersionNumber_decode_ber;
der_type_encoder_f RapReleaseVersionNumber_encode_der;
xer_type_decoder_f RapReleaseVersionNumber_decode_xer;
xer_type_encoder_f RapReleaseVersionNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RapReleaseVersionNumber_H_ */
#include <asn_internal.h>
