/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_RecEntityInformation_H_
#define	_RecEntityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RecEntityCode.h"
#include "RecEntityType.h"
#include "RecEntityId.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RecEntityInformation */
typedef struct RecEntityInformation {
	RecEntityCode_t	*recEntityCode	/* OPTIONAL */;
	RecEntityType_t	*recEntityType	/* OPTIONAL */;
	RecEntityId_t	*recEntityId	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RecEntityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RecEntityInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _RecEntityInformation_H_ */
#include <asn_internal.h>
