/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_ScuBasicInformation_H_
#define	_ScuBasicInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChargedPartyStatus.h"
#include "NonChargedNumber.h"
#include "ClirIndicator.h"
#include "OriginatingNetwork.h"
#include "DestinationNetwork.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ScuChargeableSubscriber;

/* ScuBasicInformation */
typedef struct ScuBasicInformation {
	struct ScuChargeableSubscriber	*chargeableSubscriber	/* OPTIONAL */;
	ChargedPartyStatus_t	*chargedPartyStatus	/* OPTIONAL */;
	NonChargedNumber_t	*nonChargedNumber	/* OPTIONAL */;
	ClirIndicator_t	*clirIndicator	/* OPTIONAL */;
	OriginatingNetwork_t	*originatingNetwork	/* OPTIONAL */;
	DestinationNetwork_t	*destinationNetwork	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScuBasicInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScuBasicInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ScuChargeableSubscriber.h"

#endif	/* _ScuBasicInformation_H_ */
#include <asn_internal.h>
