/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_ServingBid_H_
#define	_ServingBid_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Bid.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ServingBid */
typedef Bid_t	 ServingBid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServingBid;
asn_struct_free_f ServingBid_free;
asn_struct_print_f ServingBid_print;
asn_constr_check_f ServingBid_constraint;
ber_type_decoder_f ServingBid_decode_ber;
der_type_encoder_f ServingBid_encode_der;
xer_type_decoder_f ServingBid_decode_xer;
xer_type_encoder_f ServingBid_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServingBid_H_ */
#include <asn_internal.h>
