/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "ServiceCentreUsage.h"

static asn_TYPE_member_t asn_MBR_ServiceCentreUsage_1[] = {
	{ ATF_POINTER, 8, offsetof(struct ServiceCentreUsage, basicInformation),
		(ASN_TAG_CLASS_APPLICATION | (191 << 2)),
		0,
		&asn_DEF_ScuBasicInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"basicInformation"
		},
	{ ATF_POINTER, 7, offsetof(struct ServiceCentreUsage, rapFileSequenceNumber),
		(ASN_TAG_CLASS_APPLICATION | (181 << 2)),
		0,
		&asn_DEF_RapFileSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rapFileSequenceNumber"
		},
	{ ATF_POINTER, 6, offsetof(struct ServiceCentreUsage, servingNetwork),
		(ASN_TAG_CLASS_APPLICATION | (195 << 2)),
		0,
		&asn_DEF_ServingNetwork,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servingNetwork"
		},
	{ ATF_POINTER, 5, offsetof(struct ServiceCentreUsage, recEntityCode),
		(ASN_TAG_CLASS_APPLICATION | (184 << 2)),
		0,
		&asn_DEF_RecEntityCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recEntityCode"
		},
	{ ATF_POINTER, 4, offsetof(struct ServiceCentreUsage, chargeInformation),
		(ASN_TAG_CLASS_APPLICATION | (69 << 2)),
		0,
		&asn_DEF_ChargeInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargeInformation"
		},
	{ ATF_POINTER, 3, offsetof(struct ServiceCentreUsage, scuChargeType),
		(ASN_TAG_CLASS_APPLICATION | (192 << 2)),
		0,
		&asn_DEF_ScuChargeType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"scuChargeType"
		},
	{ ATF_POINTER, 2, offsetof(struct ServiceCentreUsage, scuTimeStamps),
		(ASN_TAG_CLASS_APPLICATION | (193 << 2)),
		0,
		&asn_DEF_ScuTimeStamps,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"scuTimeStamps"
		},
	{ ATF_POINTER, 1, offsetof(struct ServiceCentreUsage, operatorSpecInformation),
		(ASN_TAG_CLASS_APPLICATION | (162 << 2)),
		0,
		&asn_DEF_OperatorSpecInfoList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operatorSpecInformation"
		},
};
static ber_tlv_tag_t asn_DEF_ServiceCentreUsage_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ServiceCentreUsage_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (69 << 2)), 4, 0, 0 }, /* chargeInformation */
    { (ASN_TAG_CLASS_APPLICATION | (162 << 2)), 7, 0, 0 }, /* operatorSpecInformation */
    { (ASN_TAG_CLASS_APPLICATION | (181 << 2)), 1, 0, 0 }, /* rapFileSequenceNumber */
    { (ASN_TAG_CLASS_APPLICATION | (184 << 2)), 3, 0, 0 }, /* recEntityCode */
    { (ASN_TAG_CLASS_APPLICATION | (191 << 2)), 0, 0, 0 }, /* basicInformation */
    { (ASN_TAG_CLASS_APPLICATION | (192 << 2)), 5, 0, 0 }, /* scuChargeType */
    { (ASN_TAG_CLASS_APPLICATION | (193 << 2)), 6, 0, 0 }, /* scuTimeStamps */
    { (ASN_TAG_CLASS_APPLICATION | (195 << 2)), 2, 0, 0 } /* servingNetwork */
};
static asn_SEQUENCE_specifics_t asn_SPC_ServiceCentreUsage_specs_1 = {
	sizeof(struct ServiceCentreUsage),
	offsetof(struct ServiceCentreUsage, _asn_ctx),
	asn_MAP_ServiceCentreUsage_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	7,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ServiceCentreUsage = {
	"ServiceCentreUsage",
	"ServiceCentreUsage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ServiceCentreUsage_tags_1,
	sizeof(asn_DEF_ServiceCentreUsage_tags_1)
		/sizeof(asn_DEF_ServiceCentreUsage_tags_1[0]) - 1, /* 1 */
	asn_DEF_ServiceCentreUsage_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServiceCentreUsage_tags_1)
		/sizeof(asn_DEF_ServiceCentreUsage_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ServiceCentreUsage_1,
	8,	/* Elements count */
	&asn_SPC_ServiceCentreUsage_specs_1	/* Additional specs */
};

