/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_SMSOriginator_H_
#define	_SMSOriginator_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SMSOriginator */
typedef AsciiString_t	 SMSOriginator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SMSOriginator;
asn_struct_free_f SMSOriginator_free;
asn_struct_print_f SMSOriginator_print;
asn_constr_check_f SMSOriginator_constraint;
ber_type_decoder_f SMSOriginator_decode_ber;
der_type_encoder_f SMSOriginator_encode_der;
xer_type_decoder_f SMSOriginator_decode_xer;
xer_type_encoder_f SMSOriginator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SMSOriginator_H_ */
#include <asn_internal.h>
