/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_TaxationList_H_
#define	_TaxationList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Taxation;

/* TaxationList */
typedef struct TaxationList {
	A_SEQUENCE_OF(struct Taxation) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TaxationList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TaxationList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Taxation.h"

#endif	/* _TaxationList_H_ */
#include <asn_internal.h>
