/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "ThreeGcamelDestination.h"

static asn_TYPE_member_t asn_MBR_ThreeGcamelDestination_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ThreeGcamelDestination, choice.camelDestinationNumber),
		(ASN_TAG_CLASS_APPLICATION | (404 << 2)),
		0,
		&asn_DEF_CamelDestinationNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"camelDestinationNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ThreeGcamelDestination, choice.gprsDestination),
		(ASN_TAG_CLASS_APPLICATION | (116 << 2)),
		0,
		&asn_DEF_GprsDestination,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gprsDestination"
		},
};
static ber_tlv_tag_t asn_DEF_ThreeGcamelDestination_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (431 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ThreeGcamelDestination_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (116 << 2)), 1, 0, 0 }, /* gprsDestination */
    { (ASN_TAG_CLASS_APPLICATION | (404 << 2)), 0, 0, 0 } /* camelDestinationNumber */
};
static asn_CHOICE_specifics_t asn_SPC_ThreeGcamelDestination_specs_1 = {
	sizeof(struct ThreeGcamelDestination),
	offsetof(struct ThreeGcamelDestination, _asn_ctx),
	offsetof(struct ThreeGcamelDestination, present),
	sizeof(((struct ThreeGcamelDestination *)0)->present),
	asn_MAP_ThreeGcamelDestination_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ThreeGcamelDestination = {
	"ThreeGcamelDestination",
	"ThreeGcamelDestination",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	asn_DEF_ThreeGcamelDestination_tags_1,
	sizeof(asn_DEF_ThreeGcamelDestination_tags_1)
		/sizeof(asn_DEF_ThreeGcamelDestination_tags_1[0]), /* 1 */
	asn_DEF_ThreeGcamelDestination_tags_1,	/* Same as above */
	sizeof(asn_DEF_ThreeGcamelDestination_tags_1)
		/sizeof(asn_DEF_ThreeGcamelDestination_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ThreeGcamelDestination_1,
	2,	/* Elements count */
	&asn_SPC_ThreeGcamelDestination_specs_1	/* Additional specs */
};

