/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "TrackingCustomerInformation.h"

static asn_TYPE_member_t asn_MBR_TrackingCustomerInformation_1[] = {
	{ ATF_POINTER, 4, offsetof(struct TrackingCustomerInformation, trackingCustomerIdList),
		(ASN_TAG_CLASS_APPLICATION | (299 << 2)),
		0,
		&asn_DEF_TrackingCustomerIdList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackingCustomerIdList"
		},
	{ ATF_POINTER, 3, offsetof(struct TrackingCustomerInformation, trackingCustomerHomeIdList),
		(ASN_TAG_CLASS_APPLICATION | (365 << 2)),
		0,
		&asn_DEF_TrackingCustomerHomeIdList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackingCustomerHomeIdList"
		},
	{ ATF_POINTER, 2, offsetof(struct TrackingCustomerInformation, trackingCustomerLocList),
		(ASN_TAG_CLASS_APPLICATION | (368 << 2)),
		0,
		&asn_DEF_TrackingCustomerLocList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackingCustomerLocList"
		},
	{ ATF_POINTER, 1, offsetof(struct TrackingCustomerInformation, trackingCustomerEquipment),
		(ASN_TAG_CLASS_APPLICATION | (371 << 2)),
		0,
		&asn_DEF_TrackingCustomerEquipment,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackingCustomerEquipment"
		},
};
static ber_tlv_tag_t asn_DEF_TrackingCustomerInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (298 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TrackingCustomerInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (299 << 2)), 0, 0, 0 }, /* trackingCustomerIdList */
    { (ASN_TAG_CLASS_APPLICATION | (365 << 2)), 1, 0, 0 }, /* trackingCustomerHomeIdList */
    { (ASN_TAG_CLASS_APPLICATION | (368 << 2)), 2, 0, 0 }, /* trackingCustomerLocList */
    { (ASN_TAG_CLASS_APPLICATION | (371 << 2)), 3, 0, 0 } /* trackingCustomerEquipment */
};
static asn_SEQUENCE_specifics_t asn_SPC_TrackingCustomerInformation_specs_1 = {
	sizeof(struct TrackingCustomerInformation),
	offsetof(struct TrackingCustomerInformation, _asn_ctx),
	asn_MAP_TrackingCustomerInformation_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TrackingCustomerInformation = {
	"TrackingCustomerInformation",
	"TrackingCustomerInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TrackingCustomerInformation_tags_1,
	sizeof(asn_DEF_TrackingCustomerInformation_tags_1)
		/sizeof(asn_DEF_TrackingCustomerInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_TrackingCustomerInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_TrackingCustomerInformation_tags_1)
		/sizeof(asn_DEF_TrackingCustomerInformation_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_TrackingCustomerInformation_1,
	4,	/* Elements count */
	&asn_SPC_TrackingCustomerInformation_specs_1	/* Additional specs */
};

