/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "TrackedCustomerInformation.h"

static asn_TYPE_member_t asn_MBR_TrackedCustomerInformation_1[] = {
	{ ATF_POINTER, 4, offsetof(struct TrackedCustomerInformation, trackedCustomerIdList),
		(ASN_TAG_CLASS_APPLICATION | (370 << 2)),
		0,
		&asn_DEF_TrackedCustomerIdList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackedCustomerIdList"
		},
	{ ATF_POINTER, 3, offsetof(struct TrackedCustomerInformation, trackedCustomerHomeIdList),
		(ASN_TAG_CLASS_APPLICATION | (376 << 2)),
		0,
		&asn_DEF_TrackedCustomerHomeIdList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackedCustomerHomeIdList"
		},
	{ ATF_POINTER, 2, offsetof(struct TrackedCustomerInformation, trackedCustomerLocList),
		(ASN_TAG_CLASS_APPLICATION | (379 << 2)),
		0,
		&asn_DEF_TrackedCustomerLocList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackedCustomerLocList"
		},
	{ ATF_POINTER, 1, offsetof(struct TrackedCustomerInformation, trackedCustomerEquipment),
		(ASN_TAG_CLASS_APPLICATION | (381 << 2)),
		0,
		&asn_DEF_TrackedCustomerEquipment,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trackedCustomerEquipment"
		},
};
static ber_tlv_tag_t asn_DEF_TrackedCustomerInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (367 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TrackedCustomerInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (370 << 2)), 0, 0, 0 }, /* trackedCustomerIdList */
    { (ASN_TAG_CLASS_APPLICATION | (376 << 2)), 1, 0, 0 }, /* trackedCustomerHomeIdList */
    { (ASN_TAG_CLASS_APPLICATION | (379 << 2)), 2, 0, 0 }, /* trackedCustomerLocList */
    { (ASN_TAG_CLASS_APPLICATION | (381 << 2)), 3, 0, 0 } /* trackedCustomerEquipment */
};
static asn_SEQUENCE_specifics_t asn_SPC_TrackedCustomerInformation_specs_1 = {
	sizeof(struct TrackedCustomerInformation),
	offsetof(struct TrackedCustomerInformation, _asn_ctx),
	asn_MAP_TrackedCustomerInformation_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TrackedCustomerInformation = {
	"TrackedCustomerInformation",
	"TrackedCustomerInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TrackedCustomerInformation_tags_1,
	sizeof(asn_DEF_TrackedCustomerInformation_tags_1)
		/sizeof(asn_DEF_TrackedCustomerInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_TrackedCustomerInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_TrackedCustomerInformation_tags_1)
		/sizeof(asn_DEF_TrackedCustomerInformation_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_TrackedCustomerInformation_1,
	4,	/* Elements count */
	&asn_SPC_TrackedCustomerInformation_specs_1	/* Additional specs */
};

