/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#include "TransferBatch.h"

static asn_TYPE_member_t asn_MBR_TransferBatch_1[] = {
	{ ATF_POINTER, 5, offsetof(struct TransferBatch, batchControlInfo),
		(ASN_TAG_CLASS_APPLICATION | (4 << 2)),
		0,
		&asn_DEF_BatchControlInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"batchControlInfo"
		},
	{ ATF_POINTER, 4, offsetof(struct TransferBatch, accountingInfo),
		(ASN_TAG_CLASS_APPLICATION | (5 << 2)),
		0,
		&asn_DEF_AccountingInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accountingInfo"
		},
	{ ATF_POINTER, 3, offsetof(struct TransferBatch, networkInfo),
		(ASN_TAG_CLASS_APPLICATION | (6 << 2)),
		0,
		&asn_DEF_NetworkInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkInfo"
		},
	{ ATF_POINTER, 2, offsetof(struct TransferBatch, callEventDetails),
		(ASN_TAG_CLASS_APPLICATION | (3 << 2)),
		0,
		&asn_DEF_CallEventDetailList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callEventDetails"
		},
	{ ATF_POINTER, 1, offsetof(struct TransferBatch, auditControlInfo),
		(ASN_TAG_CLASS_APPLICATION | (15 << 2)),
		0,
		&asn_DEF_AuditControlInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"auditControlInfo"
		},
};
static ber_tlv_tag_t asn_DEF_TransferBatch_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TransferBatch_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 3, 0, 0 }, /* callEventDetails */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 0, 0, 0 }, /* batchControlInfo */
    { (ASN_TAG_CLASS_APPLICATION | (5 << 2)), 1, 0, 0 }, /* accountingInfo */
    { (ASN_TAG_CLASS_APPLICATION | (6 << 2)), 2, 0, 0 }, /* networkInfo */
    { (ASN_TAG_CLASS_APPLICATION | (15 << 2)), 4, 0, 0 } /* auditControlInfo */
};
static asn_SEQUENCE_specifics_t asn_SPC_TransferBatch_specs_1 = {
	sizeof(struct TransferBatch),
	offsetof(struct TransferBatch, _asn_ctx),
	asn_MAP_TransferBatch_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TransferBatch = {
	"TransferBatch",
	"TransferBatch",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TransferBatch_tags_1,
	sizeof(asn_DEF_TransferBatch_tags_1)
		/sizeof(asn_DEF_TransferBatch_tags_1[0]) - 1, /* 1 */
	asn_DEF_TransferBatch_tags_1,	/* Same as above */
	sizeof(asn_DEF_TransferBatch_tags_1)
		/sizeof(asn_DEF_TransferBatch_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_TransferBatch_1,
	5,	/* Elements count */
	&asn_SPC_TransferBatch_specs_1	/* Additional specs */
};

