/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP-0312"
 */

#ifndef	_TransferCutOffTimeStamp_H_
#define	_TransferCutOffTimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DateTimeLong.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TransferCutOffTimeStamp */
typedef DateTimeLong_t	 TransferCutOffTimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransferCutOffTimeStamp;
asn_struct_free_f TransferCutOffTimeStamp_free;
asn_struct_print_f TransferCutOffTimeStamp_print;
asn_constr_check_f TransferCutOffTimeStamp_constraint;
ber_type_decoder_f TransferCutOffTimeStamp_decode_ber;
der_type_encoder_f TransferCutOffTimeStamp_encode_der;
xer_type_decoder_f TransferCutOffTimeStamp_decode_xer;
xer_type_encoder_f TransferCutOffTimeStamp_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TransferCutOffTimeStamp_H_ */
#include <asn_internal.h>
